settings {
   logfile    = "/tmp/lsyncd_wayfarers.log",
   statusFile = "/tmp/lsyncd_wayfarers.status",
   nodaemon   = true,
}
local user_home = os.getenv("HOME")
sync {
    source  = user_home .. "/git/bga-wayfarers/",
    target  = user_home .. "/Develop/bga/remote/wayfarers/",
    default.rsync,
    delay  = 1,
    exclude = { ".git", ".project", ".settings" , ".buildpath", "node_modules",  "img/game*.png", "*.tmp*", "* *", "*.out", "tests" },
    rsync     = { 
        omit_dir_times = true
    }
}
