<?php

declare(strict_types=1);

namespace Bga\Games\wayfarers;

class Material {
    const RET_OK = 0;
    const ERR_COST = 1;
    const ERR_PREREQ = 2;
    const ERR_OCCUPIED = 3;
    const ERR_MAX = 4;
    const ERR_NONE_LEFT = 5;
    const ERR_NOT_APPLICABLE = 6;

    private array $token_types;
    private bool $adjusted = false;
    public function __construct() {
        $this->token_types = [
            // #error codes - MANUAL ENTRY
            "err_0" => [
                //
                "code" => Material::RET_OK,
                "type" => "err",
                "name" => clienttranslate("Ok"),
            ],
            "err_1" => [
                //
                "code" => Material::ERR_COST,
                "type" => "err",
                "name" => clienttranslate("Insufficient Resources"),
            ],

            "err_2" => [
                //
                "code" => Material::ERR_PREREQ,
                "type" => "err",
                "name" => clienttranslate("Prerequisites are not fulfilled"),
            ],
            "err_3" => [
                //
                "code" => Material::ERR_OCCUPIED,
                "type" => "err",
                "name" => clienttranslate("Location is occupied"),
            ],
            "err_4" => [
                //
                "code" => Material::ERR_MAX,
                "type" => "err",
                "name" => clienttranslate("Maximum capacity is reached"),
            ],
            "err_5" => [
                //
                "code" => Material::ERR_NONE_LEFT,
                "type" => "err",
                "name" => clienttranslate("None left"),
            ],

            "err_6" => [
                //
                "code" => Material::ERR_NOT_APPLICABLE,
                "type" => "err",
                "name" => clienttranslate("Not applicable"),
            ],

            /* --- gen php begin loc_material --- */
            "deck_folk" => [
                "type" => "location",
                "showtooltip" => 0,
                "create" => 0,
                "name" => clienttranslate("Townsfolk Cards"),
                "location" => "supply",
                "scope" => "global",
                "counter" => "public",
                "content" => "hidden",
            ],
            "deck_land" => [
                "type" => "location",
                "showtooltip" => 0,
                "create" => 0,
                "name" => clienttranslate("Land Cards"),
                "location" => "supply",
                "scope" => "global",
                "counter" => "public",
                "content" => "hidden",
            ],
            "deck_water" => [
                "type" => "location",
                "showtooltip" => 0,
                "create" => 0,
                "name" => clienttranslate("Water Cards"),
                "location" => "supply",
                "scope" => "global",
                "counter" => "public",
                "content" => "hidden",
            ],
            "deck_space" => [
                "type" => "location",
                "showtooltip" => 0,
                "create" => 0,
                "name" => clienttranslate("Space Cards"),
                "location" => "supply",
                "scope" => "global",
                "counter" => "public",
                "content" => "hidden",
            ],
            "deck_insp" => [
                "type" => "location",
                "showtooltip" => 0,
                "create" => 0,
                "name" => clienttranslate("Inspiration Cards"),
                "location" => "supply",
                "scope" => "global",
                "counter" => "public",
                "content" => "hidden",
            ],
            "limbo" => [
                "type" => "location",
                "showtooltip" => 0,
                "create" => 0,
                "name" => clienttranslate("Limbo"),
                "scope" => "global",
                "counter" => "hidden",
                "content" => "hidden",
            ],
            "tableau" => [
                "type" => "location",
                "showtooltip" => 0,
                "create" => 0,
                "name" => clienttranslate("Player Area"),
                "location" => "players_panels",
                "scope" => "player",
                "counter" => "hidden",
                "content" => "public",
            ],
            "hand" => [
                "type" => "location",
                "showtooltip" => 0,
                "create" => 0,
                "name" => clienttranslate("Player Hand"),
                "location" => "players_panels",
                "scope" => "player",
                "counter" => "hidden",
                "content" => "private",
            ],
            "supply" => [
                "type" => "location",
                "showtooltip" => 0,
                "create" => 0,
                "name" => clienttranslate("Supply"),
                "location" => "supply",
                "scope" => "global",
                "counter" => "public",
                "content" => "public",
            ],
            "guild_black" => [
                "type" => "location",
                "showtooltip" => 0,
                "create" => 0,
                "name" => clienttranslate("Black Guild (Science)"),
                "location" => "mainarea",
                "scope" => "global",
                "counter" => "hidden",
                "content" => "public",
            ],
            "guild_blue" => [
                "type" => "location",
                "showtooltip" => 0,
                "create" => 0,
                "name" => clienttranslate("Blue Guild (Exploration)"),
                "location" => "mainarea",
                "scope" => "global",
                "counter" => "hidden",
                "content" => "public",
            ],
            "guild_yellow" => [
                "type" => "location",
                "showtooltip" => 0,
                "create" => 0,
                "name" => clienttranslate("Yellow Guild (Trade)"),
                "location" => "mainarea",
                "scope" => "global",
                "counter" => "hidden",
                "content" => "public",
            ],
            /* --- gen php end loc_material --- */
            /* --- gen php begin op_material --- */
            "Op_nop" => [
                "type" => "nop",
                "name" => clienttranslate("None"),
            ],
            // #fake name
            "Op_barrier" => [
                "type" => "barrier",
                "name" => clienttranslate("None"),
            ],
            "Op_savepoint" => [
                "type" => "savepoint",
                "name" => clienttranslate("None"),
            ],
            "Op_or" => [
                "type" => "or",
                "name" => clienttranslate("Choice"),
            ],
            "Op_unique" => [
                "type" => "unique",
                "name" => clienttranslate("Unique Choice"),
            ],
            "Op_order" => [
                "type" => "order",
                "name" => clienttranslate("Choose Order"),
            ],
            "Op_seq" => [
                "type" => "seq",
                "name" => clienttranslate("Sequence"),
            ],
            "Op_gain" => [
                "type" => "gain",
                "name" => clienttranslate("Gain"),
            ],
            "Op_pay" => [
                "type" => "pay",
                "name" => clienttranslate("Pay"),
            ],
            "Op_paygain" => [
                "type" => "paygain",
                "name" => clienttranslate("Trade"),
            ],
            "Op_turn" => [
                "type" => "turn",
                "name" => clienttranslate("Turn"),
            ],
            "Op_rest" => [
                "type" => "rest",
                "name" => clienttranslate("Rest"),
            ],
            "Op_placeWorker" => [
                "type" => "placeWorker",
                "name" => clienttranslate("Place Worker"),
            ],
            "Op_placeDie" => [
                "type" => "placeDie",
                "name" => clienttranslate("Place Die"),
            ],
            "Op_spendInfBlue" => [
                "type" => "spendInfBlue",
                "name" => clienttranslate("Spend Blue Influence for Ship"),
            ],
            "Op_spendInfYellow" => [
                "type" => "spendInfYellow",
                "name" => clienttranslate("Spend Yellow Influence to Modify Dice"),
            ],
            "Op_cardSpace" => [
                "type" => "cardSpace",
                "name" => clienttranslate("Acquire Space Card"),
            ],
            "Op_cardFolk" => [
                "type" => "cardFolk",
                "name" => clienttranslate("Acquire Townsfolk Card"),
            ],
            "Op_cardWater" => [
                "type" => "cardWater",
                "name" => clienttranslate("Acquire Water Card"),
            ],
            "Op_cardLand" => [
                "type" => "cardLand",
                "name" => clienttranslate("Acquire Land Card"),
            ],
            "Op_cardDraw" => [
                "type" => "cardDraw",
                "name" => clienttranslate("Draw and Pick Card"),
            ],
            "Op_cardInsp" => [
                "type" => "cardInsp",
                "name" => clienttranslate("Acquire Inspiration Card"),
            ],
            "Op_cardInteract" => [
                "type" => "cardInteract",
                "name" => clienttranslate("Card Interaction"),
            ],
            "Op_upgBlack" => [
                "type" => "upgBlack",
                "name" => clienttranslate("Acquire Space Upgrade"),
            ],
            "Op_upgBlue" => [
                "type" => "upgBlue",
                "name" => clienttranslate("Acquire Water Upgrade"),
            ],
            "Op_upgGreen" => [
                "type" => "upgGreen",
                "name" => clienttranslate("Acquire Basic Upgrade"),
            ],
            "Op_upgPink" => [
                "type" => "upgPink",
                "name" => clienttranslate("Gain Special Upgrade"),
            ],
            "Op_upgYellow" => [
                "type" => "upgYellow",
                "name" => clienttranslate("Acquire Land Upgrade"),
            ],
            "Op_journal" => [
                "type" => "journal",
                "name" => clienttranslate("Journal"),
            ],
            "Op_pickWorker" => [
                "type" => "pickWorker",
                "name" => clienttranslate("Pick a Worker"),
            ],
            "Op_drawTab" => [
                "type" => "drawTab",
                "name" => clienttranslate("Refill Cards"),
            ],
            "Op_reroll" => [
                "type" => "reroll",
                "name" => clienttranslate("Refresh a Die"),
            ],
            "Op_ship" => [
                "type" => "ship",
                "name" => clienttranslate("Ship"),
            ],
            "Op_camel" => [
                "type" => "camel",
                "name" => clienttranslate("Camel"),
            ],
            "Op_telescope" => [
                "type" => "telescope",
                "name" => clienttranslate("Telescope"),
            ],
            "Op_pigeon" => [
                "type" => "pigeon",
                "name" => clienttranslate("Pigeon"),
            ],
            "Op_infAny" => [
                "type" => "infAny",
                "name" => clienttranslate("Influence on any Guild"),
            ],
            "Op_infBlue" => [
                "type" => "infBlue",
                "name" => clienttranslate("Influence on Blue"),
            ],
            "Op_infYellow" => [
                "type" => "infYellow",
                "name" => clienttranslate("Influence on Yellow"),
            ],
            "Op_infBlack" => [
                "type" => "infBlack",
                "name" => clienttranslate("Influence on Black"),
            ],
            "Op_infCard" => [
                "type" => "infCard",
                "name" => clienttranslate("Influence on Card"),
            ],
            "Op_infMove" => [
                "type" => "infMove",
                "name" => clienttranslate("Move Influence"),
            ],
            "Op_diceMod" => [
                "type" => "diceMod",
                "name" => clienttranslate("Modify Dice by +/- 1"),
            ],
            "Op_dicePlus" => [
                "type" => "dicePlus",
                "name" => clienttranslate("Modify Dice by +1"),
            ],
            "Op_diceMinus" => [
                "type" => "diceMinus",
                "name" => clienttranslate("Modify Dice by -1"),
            ],
            "Op_food" => [
                "class" => "Op_gain",
                "type" => "food",
                "name" => clienttranslate("Gain Provisions"),
            ],
            "Op_coin" => [
                "class" => "Op_gain",
                "type" => "coin",
                "name" => clienttranslate("Gain Silver"),
            ],
            "Op_n_food" => [
                "class" => "Op_pay",
                "type" => "n_food",
                "name" => clienttranslate("Pay Provisions"),
            ],
            "Op_n_coin" => [
                "class" => "Op_pay",
                "type" => "n_coin",
                "name" => clienttranslate("Pay Silver"),
            ],
            "Op_n_infBlue" => [
                "type" => "n_infBlue",
                "name" => clienttranslate("Pay Blue Influence"),
            ],
            "Op_n_infYellow" => [
                "type" => "n_infYellow",
                "name" => clienttranslate("Pay Yellow Influence"),
            ],
            "Op_n_infBlack" => [
                "type" => "n_infBlack",
                "name" => clienttranslate("Pay Black Influence"),
            ],
            "Op_finalScoring" => [
                "type" => "finalScoring",
                "name" => clienttranslate("Final Scoring"),
            ],
            /* --- gen php end op_material --- */
            /* --- gen php begin token_material --- */
            // # create is one of the numbers
            // # 0 - do not create token
            // # 1 - the token with id $id will be created, count must be set to 1 if used
            // # 2 - the token with id "${id}_{INDEX}" will be created, using count starting from 1
            // # 3 - the token with id "${id}_{COLOR}_{INDEX}" will be created, using count, per player
            // # 4 - the token with id "${id}_{COLOR}" for each player will be created, count must be 1
            // # 5 - the token with id "${id}_{INDEX}_{COLOR}" for each player will be created
            // # 6 - custom placeholders
            // #12  Workers 4 of each 3 colors
            "worker_blue" => [
                "name" => clienttranslate("Blue Worker"),
                "count" => 4,
                "type" => "worker wooden",
                "create" => 2,
                "location" => "limbo",
            ],
            "worker_yellow" => [
                "name" => clienttranslate("Yellow Worker"),
                "count" => 4,
                "type" => "worker wooden",
                "create" => 2,
                "location" => "limbo",
            ],
            "worker_green" => [
                "name" => clienttranslate("Green Worker"),
                "count" => 4,
                "type" => "worker wooden",
                "create" => 2,
                "location" => "limbo",
            ],
            // #player counters
            "tracker_coin" => [
                "name" => clienttranslate("Silver"),
                "count" => 1,
                "type" => "tracker coin",
                "create" => 4,
                "location" => "miniboard_{COLOR}",
            ],
            "tracker_food" => [
                "name" => clienttranslate("Provision"),
                "count" => 1,
                "type" => "tracker food",
                "create" => 4,
                "location" => "miniboard_{COLOR}",
            ],
            "marker" => [
                "name" => clienttranslate("Player marker"),
                "count" => 1,
                "type" => "marker wooden",
                "create" => 4,
                "location" => "tableau_{COLOR}",
            ],
            "influence" => [
                "name" => clienttranslate("Influence"),
                "count" => 15,
                "type" => "influence wooden",
                "create" => 3,
                "location" => "tableau_{COLOR}",
            ],
            "dice" => [
                "name" => clienttranslate("Player die"),
                "count" => 5,
                "type" => "dice wooden",
                "create" => 3,
                "location" => "tableau_{COLOR}",
            ],
            "used_inf_blue" => [
                "count" => 1,
                "type" => "flag",
                "create" => 4,
                "location" => "limbo",
            ],
            "used_inf_yellow" => [
                "count" => 1,
                "type" => "flag",
                "create" => 4,
                "location" => "limbo",
            ],
            "used_inf_back" => [
                "count" => 1,
                "type" => "flag",
                "create" => 4,
                "location" => "limbo",
            ],
            // #journal tiles
            "jtile" => [
                "name" => clienttranslate("Journal Tile"),
                "count" => 10,
                "type" => "jtile tile",
                "create" => 2,
                "location" => "deck_jtile",
            ],
            "upg" => [
                "name" => clienttranslate("Upgrade Tile"),
                "count" => 10,
                "type" => "upg tile",
                "create" => 2,
                "location" => "supply",
            ],
            // #cards
            // #36 Townsfolk Cards 36 Space Cards 36 Land Cards 16 Inspiration Cards 36 Water Cards 6 Scheme Cards
            "card_folk" => [
                "create" => 0,
                "name" => clienttranslate("Townsfolk"),
                "count" => 36,
                "type" => "card card_folk",
                "location" => "deck_folk",
            ],
            "card_space" => [
                "create" => 0,
                "name" => clienttranslate("Space"),
                "count" => 36,
                "type" => "card card_space",
                "location" => "deck_space",
            ],
            "card_land" => [
                "create" => 0,
                "name" => clienttranslate("Land"),
                "count" => 36,
                "type" => "card card_land",
                "location" => "deck_land",
            ],
            "card_water" => [
                "create" => 0,
                "name" => clienttranslate("Water"),
                "count" => 36,
                "type" => "card card_water",
                "location" => "deck_water",
            ],
            "card_insp" => [
                "create" => 0,
                "name" => clienttranslate("Inspiration"),
                "count" => 16,
                "type" => "card card_insp",
                "location" => "deck_insp",
            ],
            // #boards
            "mainboard_1" => [
                "create" => 1,
                "count" => 1,
                "type" => "mainboard_x left",
                "location" => "mainboardall",
            ],
            "mainboard_2" => [
                "create" => 1,
                "count" => 1,
                "type" => "mainboard_x middle",
                "location" => "mainboardall",
            ],
            "mainboard_3" => [
                "create" => 1,
                "count" => 1,
                "type" => "mainboard_x right",
                "location" => "mainboardall",
            ],
            "game_stage" => [
                "create" => 1,
                "count" => 1,
                "type" => "stage",
                "location" => "limbo",
            ],
            // #ui elements
            "die_1" => [
                "create" => 0,
                "type" => "dice wooden token die_1",
                "name" => clienttranslate("Die 1"),
                "count" => 1,
            ],
            "die_2" => [
                "create" => 0,
                "type" => "dice wooden token die_2",
                "name" => clienttranslate("Die 2"),
                "count" => 2,
            ],
            "die_3" => [
                "create" => 0,
                "type" => "dice wooden token die_3",
                "name" => clienttranslate("Die 3"),
                "count" => 3,
            ],
            "die_4" => [
                "create" => 0,
                "type" => "dice wooden token die_4",
                "name" => clienttranslate("Die 4"),
                "count" => 4,
            ],
            "die_5" => [
                "create" => 0,
                "type" => "dice wooden token die_5",
                "name" => clienttranslate("Die 5"),
                "count" => 5,
            ],
            "die_6" => [
                "create" => 0,
                "type" => "dice wooden token die_6",
                "name" => clienttranslate("Die 6"),
                "count" => 6,
            ],
            // #names of the upgrades
            "upg_green" => [
                "name" => clienttranslate("Basic Upgrade Tile"),
            ],
            "upg_blue" => [
                "name" => clienttranslate("Water Upgrade Tile"),
            ],
            "upg_yellow" => [
                "name" => clienttranslate("Land Upgrade Tile"),
            ],
            "upg_black" => [
                "name" => clienttranslate("Space Upgrade Tile"),
            ],
            "upg_pink" => [
                "name" => clienttranslate("Special Upgrade Tile"),
            ],
            // #names of the stats
            "game_vp_tags" => [
                "name" => clienttranslate("VP from Primary Tags (City, Vista, Harbour, Water)"),
            ],
            "game_vp_sets" => [
                "name" => clienttranslate("VP from Tag Sets"),
            ],
            "game_vp_space" => [
                "name" => clienttranslate("VP from Space Cards"),
            ],
            "game_vp_inspiration" => [
                "name" => clienttranslate("VP from Inspiration Cards"),
            ],
            "game_vp_caravan" => [
                "name" => clienttranslate("VP from Caravan Upgrade Tiles"),
            ],
            "game_vp_guilds" => [
                "name" => clienttranslate("VP from Guild Majorities"),
            ],
            "game_vp_total" => [
                "name" => clienttranslate("VP total"),
            ],
            // #tags
            "tag_Water" => [
                "name" => clienttranslate("Water"),
            ],
            "tag_Harbour" => [
                "name" => clienttranslate("Harbour"),
            ],
            "tag_Sea" => [
                "name" => clienttranslate("Open Water"),
            ],
            "tag_Land" => [
                "name" => clienttranslate("Land"),
            ],
            "tag_City" => [
                "name" => clienttranslate("City"),
            ],
            "tag_Vista" => [
                "name" => clienttranslate("Vista"),
            ],
            "tag_Space" => [
                "name" => clienttranslate("Space"),
            ],
            "tag_Observatory" => [
                "name" => clienttranslate("Observatory"),
            ],
            "tag_Book" => [
                "name" => clienttranslate("Book"),
            ],
            "tag_Comet" => [
                "name" => clienttranslate("Comet"),
            ],
            "tag_Stars" => [
                "name" => clienttranslate("Stars"),
            ],
            "tag_Planet" => [
                "name" => clienttranslate("Planet"),
            ],
            "tag_Sun" => [
                "name" => clienttranslate("Sun"),
            ],
            "tag_Moon" => [
                "name" => clienttranslate("Moon"),
            ],
            "tag_Library" => [
                "name" => clienttranslate("Library"),
            ],
            "tag_CardFolk" => [
                "name" => clienttranslate("Townsfolk Card"),
            ],
            "tag_UpgradeAny" => [
                "name" => clienttranslate("Any Upgrade"),
            ],
            /* --- gen php end token_material --- */

            /* --- gen php begin card_material --- */
            "card_home_1" => [
                "create" => 4,
                "t" => "home",
                "type" => "card card_home",
                "location" => "tableau_{COLOR}",
                "num" => 1,
                "tags" => "Book Observatory",
            ],
            "card_home_2" => [
                "create" => 4,
                "t" => "home",
                "type" => "card card_home",
                "location" => "tableau_{COLOR}",
                "num" => 2,
                "d" => "camel",
                "dr" => "2n_food:cardLand,coin",
                "tags" => "City",
                "name" => clienttranslate("Capital City"),
                "state" => -1,
            ],
            "card_home_3" => [
                "create" => 4,
                "t" => "home",
                "type" => "card card_home",
                "location" => "tableau_{COLOR}",
                "num" => 3,
                "d" => "ship",
                "dr" => "2n_food:cardWater",
                "tags" => "Harbour",
                "name" => clienttranslate("Capital Harbour"),
                "state" => 1,
            ],
            "card_home_10" => [
                "create" => 4,
                "t" => "home",
                "type" => "card card_home card_slot",
                "location" => "tableau_{COLOR}",
                "num" => 10,
                "d" => "telescope",
                "dr" => "(cardSpace/upgBlack)",
                "name" => clienttranslate("Capital Observatory"),
            ],
            "card_home_11" => [
                "create" => 4,
                "t" => "home",
                "type" => "card card_home card_slot",
                "location" => "tableau_{COLOR}",
                "num" => 11,
                "d" => "pigeon",
                "dr" => "(journal/(pickWorker,infAny))",
                "name" => clienttranslate("Capital Library"),
            ],
            "card_home_12" => [
                "create" => 4,
                "t" => "home",
                "type" => "card card_home card_slot",
                "location" => "tableau_{COLOR}",
                "num" => 12,
                "d" => "any",
                "dr" => "(cardFolk/2food)",
                "name" => clienttranslate("Capital Market"),
            ],
            "card_home_13" => [
                "create" => 4,
                "t" => "home",
                "type" => "card card_home card_slot",
                "location" => "tableau_{COLOR}",
                "num" => 13,
                "d" => "any",
                "dr" => "(upgGreen/2coin)",
                "name" => clienttranslate("Capital Reserve"),
            ],
            /* --- gen php end card_material --- */
            /* --- gen php begin cardfolk_material --- */
            "card_folk_114" => [
                "create" => 1,
                "ext" => 1,
                "num" => 114,
                "cost" => 1,
                "dr" => "(coin/food):(pickWorker,reroll)",
                "tags" => "Vista",
                "name" => clienttranslate("Protector"),
            ],
            "card_folk_115" => [
                "create" => 1,
                "ext" => 1,
                "num" => 115,
                "cost" => 2,
                "dr" => "food:2coin",
                "tags" => "Observatory",
                "name" => clienttranslate("Wanderer"),
            ],
            "card_folk_116" => [
                "create" => 1,
                "num" => 116,
                "cost" => 1,
                "tags" => "Harbour",
                "name" => clienttranslate("Adventurer"),
                "da" => "ship",
            ],
            "card_folk_117" => [
                "create" => 1,
                "num" => 117,
                "cost" => 0,
                "tags" => "Observatory",
                "name" => clienttranslate("Astronomer"),
                "da" => "telescope",
            ],
            "card_folk_118" => [
                "create" => 1,
                "num" => 118,
                "cost" => 2,
                "dr" => "pickWorker/infCard",
                "tags" => "Vista",
                "name" => clienttranslate("Champion"),
            ],
            "card_folk_121" => [
                "create" => 1,
                "num" => 121,
                "cost" => 2,
                "tags" => "Harbour",
                "name" => clienttranslate("Envoy"),
                "da" => "camel,pigeon",
            ],
            "card_folk_122" => [
                "create" => 1,
                "num" => 122,
                "cost" => 2,
                "tags" => "Harbour",
                "name" => clienttranslate("Envoy"),
                "da" => "ship,pigeon",
            ],
            "card_folk_123" => [
                "create" => 1,
                "num" => 123,
                "cost" => 2,
                "dr" => "coin",
                "tags" => "City",
                "name" => clienttranslate("Farmer"),
            ],
            "card_folk_124" => [
                "create" => 1,
                "num" => 124,
                "cost" => 2,
                "dr" => "food",
                "tags" => "City",
                "name" => clienttranslate("Farmer"),
            ],
            "card_folk_125" => [
                "create" => 1,
                "num" => 125,
                "cost" => 2,
                "dr" => "coin",
                "tags" => "Harbour",
                "name" => clienttranslate("Fisherman"),
            ],
            "card_folk_126" => [
                "create" => 1,
                "num" => 126,
                "cost" => 2,
                "dr" => "food",
                "tags" => "Harbour",
                "name" => clienttranslate("Fisherman"),
            ],
            "card_folk_130" => [
                "create" => 1,
                "num" => 130,
                "cost" => 0,
                "dr" => "2diceMod",
                "tags" => "Vista",
                "name" => clienttranslate("Hunter"),
            ],
            "card_folk_131" => [
                "create" => 1,
                "num" => 131,
                "cost" => 2,
                "dr" => "ship,ship",
                "tags" => "Harbour",
                "name" => clienttranslate("Invader"),
            ],
            "card_folk_132" => [
                "create" => 1,
                "num" => 132,
                "cost" => 2,
                "dr" => "pickWorker/infCard",
                "tags" => "City Harbour",
                "name" => clienttranslate("Mercenary"),
            ],
            "card_folk_133" => [
                "create" => 1,
                "num" => 133,
                "cost" => 2,
                "dr" => "coin",
                "tags" => "Vista",
                "name" => clienttranslate("Merchant"),
            ],
            "card_folk_134" => [
                "create" => 1,
                "num" => 134,
                "cost" => 2,
                "dr" => "coin",
                "tags" => "Vista",
                "name" => clienttranslate("Merchant"),
            ],
            "card_folk_135" => [
                "create" => 1,
                "num" => 135,
                "cost" => 2,
                "dr" => "food",
                "tags" => "Vista",
                "name" => clienttranslate("Merchant"),
            ],
            "card_folk_136" => [
                "create" => 1,
                "num" => 136,
                "cost" => 2,
                "dr" => "food",
                "tags" => "Vista",
                "name" => clienttranslate("Merchant"),
            ],
            "card_folk_137" => [
                "create" => 1,
                "num" => 137,
                "cost" => 1,
                "tags" => "City Harbour",
                "name" => clienttranslate("Messenger"),
                "da" => "pigeon",
            ],
            "card_folk_138" => [
                "create" => 1,
                "num" => 138,
                "cost" => 1,
                "dr" => "infCard/infMove/diceMod",
                "tags" => "City Harbour",
                "name" => clienttranslate("Rogue"),
            ],
            "card_folk_139" => [
                "create" => 1,
                "num" => 139,
                "cost" => 1,
                "dr" => "infBlue/infMove",
                "tags" => "City Harbour",
                "name" => clienttranslate("Scholar"),
            ],
            "card_folk_140" => [
                "create" => 1,
                "num" => 140,
                "cost" => 1,
                "dr" => "infYellow/infMove",
                "tags" => "City Harbour",
                "name" => clienttranslate("Scholar"),
            ],
            "card_folk_141" => [
                "create" => 1,
                "num" => 141,
                "cost" => 2,
                "dr" => "infBlack/infMove",
                "tags" => "Book Observatory",
                "name" => clienttranslate("Scholar"),
            ],
            "card_folk_142" => [
                "create" => 1,
                "num" => 142,
                "cost" => 1,
                "dr" => "infBlue/infMove",
                "tags" => "Book Observatory",
                "name" => clienttranslate("Scribe"),
            ],
            "card_folk_143" => [
                "create" => 1,
                "num" => 143,
                "cost" => 1,
                "dr" => "infYellow/infMove",
                "tags" => "Book Observatory",
                "name" => clienttranslate("Scribe"),
            ],
            "card_folk_144" => [
                "create" => 1,
                "num" => 144,
                "cost" => 2,
                "dr" => "infBlack/infMove",
                "tags" => "Vista",
                "name" => clienttranslate("Scribe"),
            ],
            "card_folk_145" => [
                "create" => 1,
                "num" => 145,
                "cost" => 2,
                "tags" => "City",
                "name" => clienttranslate("Stargazer"),
                "da" => "telescope,camel",
            ],
            "card_folk_149" => [
                "create" => 1,
                "num" => 149,
                "cost" => 1,
                "tags" => "City",
                "name" => clienttranslate("Vagrant"),
                "da" => "camel",
            ],
            "card_folk_150" => [
                "create" => 1,
                "num" => 150,
                "cost" => 1,
                "dr" => "infCard/infMove/diceMod",
                "tags" => "Vista",
                "name" => clienttranslate("Vigilante"),
            ],
            "card_folk_119" => [
                "rest" => 1,
                "create" => 1,
                "num" => 119,
                "cost" => 1,
                "dr" => "infMove,food",
                "tags" => "Water",
                "name" => clienttranslate("Enforcer"),
            ],
            "card_folk_120" => [
                "rest" => 1,
                "create" => 1,
                "num" => 120,
                "cost" => 1,
                "dr" => "infMove,food",
                "tags" => "Water",
                "name" => clienttranslate("Enforcer"),
            ],
            "card_folk_127" => [
                "rest" => 1,
                "create" => 1,
                "num" => 127,
                "cost" => 3,
                "dr" => "food,coin",
                "tags" => "Water",
                "name" => clienttranslate("Guardian"),
            ],
            "card_folk_128" => [
                "rest" => 1,
                "create" => 1,
                "num" => 128,
                "cost" => 3,
                "dr" => "2coin",
                "tags" => "Water",
                "name" => clienttranslate("Guardian"),
            ],
            "card_folk_129" => [
                "rest" => 1,
                "create" => 1,
                "num" => 129,
                "cost" => 3,
                "dr" => "2food",
                "tags" => "Water",
                "name" => clienttranslate("Guardian"),
            ],
            "card_folk_146" => [
                "rest" => 1,
                "create" => 1,
                "num" => 146,
                "cost" => 1,
                "dr" => "infBlue/infMove",
                "tags" => "Water",
                "name" => clienttranslate("Translator"),
            ],
            "card_folk_147" => [
                "rest" => 1,
                "create" => 1,
                "num" => 147,
                "cost" => 1,
                "dr" => "infYellow/infMove",
                "tags" => "Water",
                "name" => clienttranslate("Translator"),
            ],
            "card_folk_148" => [
                "rest" => 1,
                "create" => 1,
                "num" => 148,
                "cost" => 2,
                "dr" => "infBlack/infMove",
                "tags" => "Water",
                "name" => clienttranslate("Translator"),
            ],
            "card_folk_151" => [
                "rest" => 1,
                "create" => 1,
                "num" => 151,
                "cost" => 0,
                "dr" => "pickWorker/infMove",
                "tags" => "Water",
                "name" => clienttranslate("Warrior"),
            ],
            /* --- gen php end cardfolk_material --- */
            /* --- gen php begin cardland_material --- */
            // # Row 1-3: City (1-18)
            "card_land_1" => [
                "create" => 1,
                "num" => 1,
                "r" => "infYellow",
                "d" => "camel",
                "dr" => "upgYellow/2infYellow",
                "tags" => "City",
                "tor" => clienttranslate("Gain Yellow influence"),
                "todr" => clienttranslate("Acquire a Land upgrade or gain 2 Yellow influence"),
            ],
            "card_land_2" => [
                "create" => 1,
                "num" => 2,
                "r" => "infYellow",
                "d" => "camel",
                "dr" => "upgYellow/2infYellow",
                "tags" => "City",
                "tor" => clienttranslate("Gain Yellow influence"),
                "todr" => clienttranslate("Acquire a Land upgrade or gain 2 Yellow influence"),
            ],
            "card_land_3" => [
                "create" => 1,
                "num" => 3,
                "r" => "upgGreen(free)",
                "d" => "camel",
                "dr" => "upgGreen,food",
                "tags" => "City",
                "tor" => clienttranslate("Acquire a free Basic upgrade"),
                "todr" => clienttranslate("Acquire a Basic upgrade and gain 1 Provision"),
            ],
            "card_land_4" => [
                "create" => 1,
                "num" => 4,
                "r" => "infAny",
                "d" => "camel",
                "dr" => "upgGreen,infAny",
                "tags" => "City",
                "tor" => clienttranslate("Gain Influence on any guild"),
                "todr" => clienttranslate("Acquire a Basic upgrade and gain Influence on any guild"),
            ],
            "card_land_5" => [
                "create" => 1,
                "num" => 5,
                "r" => "pickWorker",
                "d" => "camel",
                "dr" => "2n_food:cardLand,pickWorker",
                "tags" => "City",
                "tor" => clienttranslate("Pick a Worker"),
                "todr" => clienttranslate("Pay 2 Provisions to acquire a Land card, then pick a Worker"),
            ],
            "card_land_6" => [
                "create" => 1,
                "num" => 6,
                "r" => "infYellow",
                "d" => "camel",
                "dr" => "2n_food:cardLand,infYellow",
                "tags" => "City",
                "tor" => clienttranslate("Gain Yellow influence"),
                "todr" => clienttranslate("Pay 2 Provisions to acquire a Land card, then gain Yellow influence"),
            ],
            "card_land_7" => [
                "create" => 1,
                "num" => 7,
                "r" => "infBlue",
                "d" => "camel",
                "dr" => "cardFolk,infBlue",
                "tags" => "City",
                "tor" => clienttranslate("Gain Blue influence"),
                "todr" => clienttranslate("Acquire a Townsfolk card and gain Blue influence"),
            ],
            "card_land_8" => [
                "create" => 1,
                "num" => 8,
                "r" => "infCard",
                "d" => "camel",
                "dr" => "cardFolk,infCard",
                "tags" => "City",
                "tor" => clienttranslate("Gain Influence on any card"),
                "todr" => clienttranslate("Acquire a Townsfolk card and gain Influence on any card"),
            ],
            "card_land_9" => [
                "create" => 1,
                "num" => 9,
                "d" => "telescope,camel",
                "dr" => "cardSpace,infBlue",
                "tags" => "City Observatory",
                "tor" => clienttranslate("Acquire a Space card and gain Blue influence"),
            ],
            "card_land_10" => [
                "create" => 1,
                "num" => 10,
                "d" => "telescope,camel",
                "dr" => "cardSpace,infYellow",
                "tags" => "City Observatory",
                "todr" => clienttranslate("Acquire a Space card and gain Yellow influence"),
            ],
            "card_land_11" => [
                "create" => 1,
                "num" => 11,
                "d" => "telescope,camel",
                "dr" => "upgBlack/2infBlack",
                "tags" => "City Observatory",
                "todr" => clienttranslate("Acquire a Space upgrade or gain 2 Black influence"),
            ],
            "card_land_12" => [
                "create" => 1,
                "num" => 12,
                "d" => "telescope,camel",
                "dr" => "upgBlack/2infBlack",
                "tags" => "City Observatory",
                "todr" => clienttranslate("Acquire a Space upgrade or gain 2 Black influence"),
            ],
            "card_land_13" => [
                "create" => 1,
                "num" => 13,
                "d" => "telescope,camel",
                "dr" => "cardSpace,infBlack",
                "tags" => "City Observatory",
                "todr" => clienttranslate("Acquire a Space card and gain Black influence"),
            ],
            "card_land_14" => [
                "create" => 1,
                "num" => 14,
                "d" => "telescope,camel",
                "dr" => "cardSpace(dis)",
                "tags" => "City Observatory",
                "todr" => clienttranslate("Acquire a discounted Space card"),
            ],
            "card_land_15" => [
                "create" => 1,
                "num" => 15,
                "r" => "infAny",
                "d" => "camel",
                "dr" => "cardFolk,journal",
                "tags" => "City Book",
                "tor" => clienttranslate("Gain Influence on any guild"),
                "todr" => clienttranslate("Acquire a Townsfolk card and gain Journal"),
            ],
            "card_land_16" => [
                "create" => 1,
                "num" => 16,
                "d" => "pigeon",
                "dr" => "infYellow,journal",
                "tags" => "City Book",
                "todr" => clienttranslate("Gain Yellow influence and Journal"),
            ],
            "card_land_17" => [
                "create" => 1,
                "num" => 17,
                "d" => "pigeon",
                "dr" => "infBlue,journal",
                "tags" => "City Book",
                "todr" => clienttranslate("Gain Blue influence and Journal"),
            ],
            "card_land_18" => [
                "create" => 1,
                "num" => 18,
                "d" => "telescope,pigeon",
                "dr" => "infBlack,journal",
                "tags" => "City Book Observatory",
                "todr" => clienttranslate("Gain Black influence and Journal"),
            ],
            // # Row 4-6: Vista (19-37)
            "card_land_19" => [
                "create" => 1,
                "num" => 19,
                "r" => "2infCard",
                "dr" => "infCard",
                "tags" => "Vista",
                "trig" => "Stars",
                "tor" => clienttranslate("Gain 2 Influence on any card"),
                "todr" => clienttranslate("Gain Influence on any card"),
            ],
            "card_land_20" => [
                "create" => 1,
                "num" => 20,
                "r" => "coin",
                "dr" => "food",
                "tags" => "Vista",
                "trig" => "Stars",
                "tor" => clienttranslate("Gain 1 Silver"),
                "todr" => clienttranslate("Gain 1 Provision"),
            ],
            "card_land_21" => [
                "create" => 1,
                "num" => 21,
                "r" => "coin",
                "dr" => "coin",
                "tags" => "Vista",
                "trig" => "Sea",
                "tor" => clienttranslate("Gain 1 Silver"),
                "todr" => clienttranslate("Gain 1 Silver"),
            ],
            "card_land_22" => [
                "create" => 1,
                "num" => 22,
                "r" => "infBlue",
                "dr" => "infBlue/infMove",
                "tags" => "Vista",
                "trig" => "Sea",
                "tor" => clienttranslate("Gain Blue influence"),
                "todr" => clienttranslate("Gain Blue influence or move Influence"),
            ],
            "card_land_23" => [
                "create" => 1,
                "num" => 23,
                "r" => "upgGreen(free)",
                "dr" => "coin/diceMod",
                "tags" => "Vista Observatory",
                "trig" => "Comet",
                "tor" => clienttranslate("Acquire a free Basic upgrade"),
                "todr" => clienttranslate("Gain 1 Silver or modify dice by +/- 1"),
            ],
            "card_land_24" => [
                "create" => 1,
                "num" => 24,
                "r" => "upgGreen(free)",
                "dr" => "food/infMove",
                "tags" => "Vista Observatory",
                "trig" => "Comet",
                "tor" => clienttranslate("Acquire a free Basic upgrade"),
                "todr" => clienttranslate("Gain 1 Provision or move Influence"),
            ],
            "card_land_25" => [
                "create" => 1,
                "num" => 25,
                "r" => "reroll",
                "dr" => "coin",
                "tags" => "Vista",
                "trig" => "Vista",
                "tor" => clienttranslate("Refresh a die"),
                "todr" => clienttranslate("Gain 1 Silver"),
            ],
            "card_land_26" => [
                "create" => 1,
                "num" => 26,
                "r" => "reroll",
                "dr" => "infBlue/infMove",
                "tags" => "Vista",
                "trig" => "Vista",
                "tor" => clienttranslate("Refresh a die"),
                "todr" => clienttranslate("Gain Blue influence or move Influence"),
            ],
            "card_land_27" => [
                "create" => 1,
                "num" => 27,
                "r" => "2coin",
                "dr" => "food",
                "tags" => "Vista",
                "trig" => "Planet/Sun/Moon",
                "tor" => clienttranslate("Gain 2 Silver"),
                "todr" => clienttranslate("Gain 1 Provision"),
            ],
            "card_land_28" => [
                "create" => 1,
                "num" => 28,
                "r" => "2coin",
                "dr" => "pickWorker",
                "tags" => "Vista",
                "trig" => "Planet/Sun/Moon",
                "tor" => clienttranslate("Gain 2 Silver"),
                "todr" => clienttranslate("Pick a Worker"),
            ],
            "card_land_29" => [
                "create" => 1,
                "num" => 29,
                "r" => "reroll",
                "dr" => "coin",
                "tags" => "Vista",
                "trig" => "City",
                "tor" => clienttranslate("Refresh a die"),
                "todr" => clienttranslate("Gain 1 Silver"),
            ],
            "card_land_30" => [
                "create" => 1,
                "num" => 30,
                "r" => "reroll",
                "dr" => "infYellow/infMove",
                "tags" => "Vista",
                "trig" => "City",
                "tor" => clienttranslate("Refresh a die"),
                "todr" => clienttranslate("Gain Yellow influence or move Influence"),
            ],
            "card_land_31" => [
                "create" => 1,
                "num" => 31,
                "r" => "2coin",
                "dr" => "diceMod,infMove",
                "tags" => "Vista",
                "trig" => "CardFolk",
                "tor" => clienttranslate("Gain 2 Silver"),
                "todr" => clienttranslate("Modify dice by +/- 1 and move Influence"),
            ],
            "card_land_32" => [
                "create" => 1,
                "num" => 32,
                "r" => "infCard",
                "dr" => "infCard",
                "tags" => "Vista",
                "trig" => "CardFolk",
                "tor" => clienttranslate("Gain Influence on any card"),
                "todr" => clienttranslate("Gain Influence on any card"),
            ],
            "card_land_33" => [
                "create" => 1,
                "num" => 33,
                "r" => "coin",
                "dr" => "coin",
                "tags" => "Vista",
                "trig" => "Harbour",
                "tor" => clienttranslate("Gain 1 Silver"),
                "todr" => clienttranslate("Gain 1 Silver"),
            ],
            "card_land_34" => [
                "create" => 1,
                "num" => 34,
                "r" => "infYellow",
                "dr" => "infYellow/infMove",
                "tags" => "Vista",
                "trig" => "Harbour",
                "tor" => clienttranslate("Gain Yellow influence"),
                "todr" => clienttranslate("Gain Yellow influence or move Influence"),
            ],
            "card_land_35" => [
                "create" => 1,
                "num" => 35,
                "r" => "reroll",
                "dr" => "journal",
                "tags" => "Vista",
                "trig" => "Observatory/Book",
                "tor" => clienttranslate("Refresh a die"),
                "todr" => clienttranslate("Gain Journal"),
            ],
            "card_land_36" => [
                "create" => 1,
                "num" => 36,
                "r" => "reroll",
                "dr" => "food/coin",
                "tags" => "Vista",
                "trig" => "Observatory/Book",
                "tor" => clienttranslate("Refresh a die"),
                "todr" => clienttranslate("Gain 1 Provision or 1 Silver"),
            ],
            // # Row 7: City (38)
            "card_land_37" => [
                "create" => 1,
                "num" => 37,
                "r" => "coin",
                "dr" => "food",
                "tags" => "Vista",
                "trig" => "UpgradeAny",
                "tor" => clienttranslate("Gain 1 Silver"),
                "todr" => clienttranslate("Gain 1 Provision"),
            ],
            "card_land_38" => [
                "create" => 1,
                "num" => 38,
                "d" => "camel,pigeon",
                "dr" => "2n_food:cardLand,journal",
                "tags" => "City Book",
                "todr" => clienttranslate("Pay 2 Provisions to acquire a Land card, then gain Journal"),
            ],
            /* --- gen php end cardland_material --- */
            /* --- gen php begin cardwater_material --- */
            // # Water Cards (39-76) - 6x7 sprite
            "card_water_39" => [
                "create" => 1,
                "ext" => 1,
                "num" => 39,
                "d" => "2telescope",
                "dr" => "4n_coin:cardSpace(draw)",
                "tags" => "Harbour Observatory",
                "c1" => "xx__",
                "c2" => "_xxx",
                "todr" => clienttranslate("Pay 4 Silver to draw and acquire a Space card"),
            ],
            "card_water_40" => [
                "create" => 1,
                "ext" => 1,
                "num" => 40,
                "r" => "cardLand(draw1)",
                "tags" => "Sea",
                "c1" => "___",
                "c2" => "___x",
                "tor" => clienttranslate("Draw and acquire 1 Land card"),
            ],
            "card_water_41" => [
                "create" => 1,
                "num" => 41,
                "d" => "pigeon",
                "dr" => "food,journal",
                "tags" => "Harbour Book",
                "c1" => "__x_",
                "c2" => "bx_x",
                "todr" => clienttranslate("Gain 1 Provision and Journal"),
            ],
            "card_water_42" => [
                "create" => 1,
                "num" => 42,
                "d" => "pigeon",
                "dr" => "coin,journal",
                "tags" => "Harbour Book",
                "c1" => "__x_",
                "c2" => "u_xx",
                "todr" => clienttranslate("Gain 1 Silver and Journal"),
            ],
            "card_water_43" => [
                "create" => 1,
                "num" => 43,
                "d" => "pigeon",
                "dr" => "infCard,journal",
                "tags" => "Harbour Book",
                "c1" => "x__x",
                "c2" => "yxxx",
                "todr" => clienttranslate("Gain Influence on any card and Journal"),
            ],
            "card_water_44" => [
                "create" => 1,
                "num" => 44,
                "d" => "ship,ship",
                "dr" => "n_food:cardWater",
                "tags" => "Harbour Book",
                "c1" => "_xx_",
                "c2" => "yx__",
                "todr" => clienttranslate("Pay 1 Provision to acquire a Water card"),
            ],
            "card_water_45" => [
                "create" => 1,
                "num" => 45,
                "d" => "ship",
                "dr" => "2n_food:cardWater,coin",
                "tags" => "Harbour",
                "c1" => "_x_x",
                "c2" => "ux_x",
                "todr" => clienttranslate("Pay 2 Provisions to acquire a Water card, then gain Silver"),
            ],
            "card_water_46" => [
                "create" => 1,
                "num" => 46,
                "d" => "ship",
                "dr" => "2n_food:cardWater,pickWorker",
                "tags" => "Harbour",
                "c1" => "_x_x",
                "c2" => "__xx",
                "todr" => clienttranslate("Pay 2 Provisions to acquire a Water card, then pick a Worker"),
            ],
            "card_water_47" => [
                "create" => 1,
                "num" => 47,
                "d" => "ship",
                "dr" => "upgBlue/(infBlue,infBlue)",
                "tags" => "Harbour",
                "c1" => "xx__",
                "c2" => "u_x_",
                "todr" => clienttranslate("Acquire a Water upgrade or gain 2 Blue influence"),
            ],
            "card_water_48" => [
                "create" => 1,
                "num" => 48,
                "d" => "ship",
                "dr" => "upgBlue/(infBlue,infBlue)",
                "tags" => "Harbour",
                "c1" => "__xx",
                "c2" => "yx__",
                "todr" => clienttranslate("Acquire a Water upgrade or gain 2 Blue influence"),
            ],
            "card_water_49" => [
                "create" => 1,
                "num" => 49,
                "d" => "ship",
                "dr" => "reroll,diceMod,food",
                "tags" => "Harbour",
                "c1" => "_xx_",
                "c2" => "uxx_",
                "todr" => clienttranslate("Refresh a die, modify dice by +/- 1, then gain 1 Provision"),
            ],
            "card_water_50" => [
                "create" => 1,
                "num" => 50,
                "d" => "ship,ship",
                "dr" => "pickWorker,reroll,infCard",
                "tags" => "Harbour",
                "c1" => "__xx",
                "c2" => "u__x",
                "todr" => clienttranslate("Pick a Worker, refresh a die, then gain Influence on any card"),
            ],
            "card_water_51" => [
                "create" => 1,
                "num" => 51,
                "d" => "ship,ship",
                "dr" => "infYellow,infBlack,coin",
                "tags" => "Harbour",
                "c1" => "xx__",
                "c2" => "__xx",
                "todr" => clienttranslate("Gain Yellow influence, Black influence, and 1 Silver"),
            ],
            "card_water_52" => [
                "create" => 1,
                "num" => 52,
                "d" => "ship,ship",
                "dr" => "infBlue,infBlack,food",
                "tags" => "Harbour",
                "c1" => "x_x_",
                "c2" => "yx__",
                "todr" => clienttranslate("Gain Blue influence, Black influence, and 1 Provision"),
            ],
            "card_water_53" => [
                "create" => 1,
                "num" => 53,
                "d" => "ship,ship",
                "dr" => "cardFolk(free)",
                "tags" => "Harbour",
                "c1" => "x___",
                "c2" => "_xx_",
                "todr" => clienttranslate("Acquire a free Townsfolk card"),
            ],
            "card_water_54" => [
                "create" => 1,
                "num" => 54,
                "d" => "ship",
                "dr" => "food,cardFolk",
                "tags" => "Harbour",
                "c1" => "_x_x",
                "c2" => "_xx_",
                "todr" => clienttranslate("Acquire a Townsfolk card and gain Provision"),
            ],
            "card_water_55" => [
                "create" => 1,
                "num" => 55,
                "d" => "ship,ship",
                "dr" => "4food",
                "tags" => "Harbour",
                "c1" => "_x_x",
                "c2" => "__xx",
                "todr" => clienttranslate("Gain 4 Provisions"),
            ],
            "card_water_56" => [
                "create" => 1,
                "num" => 56,
                "d" => "ship,ship",
                "dr" => "4coin",
                "tags" => "Harbour",
                "c1" => "x_x_",
                "c2" => "__xx",
                "todr" => clienttranslate("Gain 4 Silver"),
            ],
            "card_water_57" => [
                "create" => 1,
                "num" => 57,
                "d" => "ship",
                "dr" => "infCard,2coin",
                "tags" => "Harbour",
                "c1" => "_x_x",
                "c2" => "bxxx",
                "todr" => clienttranslate("Gain Influence on any card and gain 2 Silver"),
            ],
            "card_water_58" => [
                "create" => 1,
                "num" => 58,
                "d" => "ship",
                "dr" => "pickWorker,2food",
                "tags" => "Harbour",
                "c1" => "xx__",
                "c2" => "_x_x",
                "todr" => clienttranslate("Pick a Worker and gain 2 Provisions"),
            ],
            "card_water_59" => [
                "create" => 1,
                "num" => 59,
                "r" => "infBlack,coin,food,infCard",
                "tags" => "Sea",
                "c1" => "_x__",
                "c2" => "bxxx",
                "tor" => clienttranslate("Gain Black influence, 1 Silver, 1 Provision, and Influence on any card"),
            ],
            "card_water_60" => [
                "create" => 1,
                "num" => 60,
                "r" => "2coin,reroll",
                "tags" => "Sea",
                "c1" => "__xx",
                "c2" => "_xx_",
                "tor" => clienttranslate("Gain 2 Silver and refresh a die"),
            ],
            "card_water_61" => [
                "create" => 1,
                "num" => 61,
                "r" => "upgBlack(free)",
                "tags" => "Sea",
                "c1" => "___x",
                "c2" => "u___",
                "tor" => clienttranslate("Acquire a free Space upgrade"),
            ],
            "card_water_62" => [
                "create" => 1,
                "num" => 62,
                "r" => "upgGreen(free),diceMod",
                "tags" => "Sea",
                "c1" => "x__x",
                "c2" => "b_x_",
                "tor" => clienttranslate("Acquire a free Basic upgrade and modify dice by +/- 1"),
            ],
            "card_water_63" => [
                "create" => 1,
                "num" => 63,
                "r" => "upgYellow(free)",
                "tags" => "Sea",
                "c1" => "_x__",
                "c2" => "_x__",
                "tor" => clienttranslate("Acquire a free Land upgrade"),
            ],
            "card_water_64" => [
                "create" => 1,
                "num" => 64,
                "r" => "upgBlue(free)",
                "tags" => "Sea",
                "c1" => "__x_",
                "c2" => "__x_",
                "tor" => clienttranslate("Acquire a free Water upgrade"),
            ],
            "card_water_65" => [
                "create" => 1,
                "num" => 65,
                "r" => "3food",
                "tags" => "Sea",
                "c1" => "__xx",
                "c2" => "_xx_",
                "tor" => clienttranslate("Gain 3 Provisions"),
            ],
            "card_water_66" => [
                "create" => 1,
                "num" => 66,
                "r" => "3coin",
                "tags" => "Sea",
                "c1" => "xx__",
                "c2" => "_xx_",
                "tor" => clienttranslate("Gain 3 Silver"),
            ],
            "card_water_67" => [
                "create" => 1,
                "num" => 67,
                "r" => "cardFolk(free)",
                "tags" => "Sea",
                "c1" => "x___",
                "c2" => "_x__",
                "tor" => clienttranslate("Acquire a free Townsfolk card"),
            ],
            "card_water_68" => [
                "create" => 1,
                "num" => 68,
                "r" => "cardInsp",
                "tags" => "Sea",
                "c1" => "____",
                "c2" => "_x__",
                "tor" => clienttranslate("Acquire an Inspiration card"),
            ],
            "card_water_69" => [
                "create" => 1,
                "num" => 69,
                "r" => "infBlack,journal",
                "tags" => "Sea",
                "c1" => "_x__",
                "c2" => "_x_x",
                "tor" => clienttranslate("Gain Black influence and Journal"),
            ],
            "card_water_70" => [
                "create" => 1,
                "num" => 70,
                "r" => "journal",
                "tags" => "Sea",
                "c1" => "__x_",
                "c2" => "ux__",
                "tor" => clienttranslate("Gain Journal"),
            ],
            "card_water_71" => [
                "create" => 1,
                "num" => 71,
                "r" => "pickWorker,reroll",
                "tags" => "Sea",
                "c1" => "x__x",
                "c2" => "y__x",
                "tor" => clienttranslate("Pick a Worker and refresh a die"),
            ],
            "card_water_72" => [
                "create" => 1,
                "num" => 72,
                "r" => "pickWorker,pickWorker",
                "tags" => "Sea",
                "c1" => "_x__",
                "c2" => "b___",
                "tor" => clienttranslate("Pick 2 Workers"),
            ],
            "card_water_73" => [
                "create" => 1,
                "num" => 73,
                "r" => "(infCard,infCard)/(infMove,infMove)",
                "tags" => "Sea",
                "c1" => "_xx_",
                "c2" => "_x_x",
                "tor" => clienttranslate("Gain 2 Influence on any card or move 2 Influence"),
            ],
            "card_water_74" => [
                "create" => 1,
                "num" => 74,
                "r" => "infBlue,infBlue",
                "tags" => "Sea",
                "c1" => "__x_",
                "c2" => "yx_x",
                "tor" => clienttranslate("Gain 2 Blue influence"),
            ],
            "card_water_75" => [
                "create" => 1,
                "num" => 75,
                "r" => "infYellow,infYellow",
                "tags" => "Sea",
                "c1" => "_x__",
                "c2" => "u_xx",
                "tor" => clienttranslate("Gain 2 Yellow influence"),
            ],
            "card_water_76" => [
                "create" => 1,
                "num" => 76,
                "r" => "infBlack,infBlack",
                "tags" => "Sea",
                "c1" => "___x",
                "c2" => "_xx_",
                "tor" => clienttranslate("Gain 2 Black influence"),
            ],
            /* --- gen php end cardwater_material --- */

            /* --- gen php begin upg_material --- */
            "upg_yellow_1" => [
                "type" => "upg upg_yellow",
                "w" => 2,
                "h" => 1,
                "num" => 1,
                "t" => "yellow",
                "r" => "dicePlus",
                "r2" => "camel",
            ],
            "upg_yellow_2" => [
                "type" => "upg upg_yellow",
                "w" => 2,
                "h" => 1,
                "num" => 2,
                "t" => "yellow",
                "r" => "camel",
                "r2" => "diceMinus",
            ],
            "upg_yellow_3" => [
                "type" => "upg upg_yellow",
                "w" => 2,
                "h" => 1,
                "num" => 3,
                "t" => "yellow",
                "r" => "pigeon",
                "r2" => "dicePlus",
            ],
            "upg_yellow_4" => [
                "type" => "upg upg_yellow",
                "w" => 2,
                "h" => 1,
                "num" => 4,
                "t" => "yellow",
                "r" => "diceMinus",
                "r2" => "pigeon",
            ],
            "upg_yellow_5" => [
                "type" => "upg upg_yellow",
                "w" => 2,
                "h" => 1,
                "num" => 5,
                "t" => "yellow",
                "r2" => "coinDis",
                "vp" => 1,
            ],
            "upg_yellow_6" => [
                "type" => "upg upg_yellow",
                "w" => 2,
                "h" => 1,
                "num" => 6,
                "t" => "yellow",
                "r" => "coinDis",
                "vp" => 1,
            ],
            "upg_blue_7" => [
                "type" => "upg upg_blue",
                "w" => 2,
                "h" => 1,
                "num" => 7,
                "t" => "blue",
                "r" => "dicePlus",
                "r2" => "ship",
            ],
            "upg_blue_8" => [
                "type" => "upg upg_blue",
                "w" => 2,
                "h" => 1,
                "num" => 8,
                "t" => "blue",
                "r" => "ship",
                "r2" => "diceMinus",
            ],
            "upg_blue_9" => [
                "type" => "upg upg_blue",
                "w" => 2,
                "h" => 1,
                "num" => 9,
                "t" => "blue",
                "r" => "ship",
                "r2" => "pigeon",
            ],
            "upg_blue_10" => [
                "type" => "upg upg_blue",
                "w" => 2,
                "h" => 1,
                "num" => 10,
                "t" => "blue",
                "r" => "pigeon",
                "r2" => "ship",
            ],
            "upg_blue_11" => [
                "type" => "upg upg_blue",
                "w" => 2,
                "h" => 1,
                "num" => 11,
                "t" => "blue",
                "r" => "coinDis",
                "r2" => "dicePlus",
            ],
            "upg_blue_12" => [
                "type" => "upg upg_blue",
                "w" => 2,
                "h" => 1,
                "num" => 12,
                "t" => "blue",
                "r" => "diceMinus",
                "r2" => "coinDis",
            ],
            "upg_black_20" => [
                "type" => "upg upg_black",
                "w" => 1,
                "h" => 2,
                "num" => 20,
                "t" => "black",
                "r" => "ship,pigeon,camel",
            ],
            "upg_black_21" => [
                "type" => "upg upg_black",
                "w" => 1,
                "h" => 2,
                "num" => 21,
                "t" => "black",
                "r" => "diceMod",
                "vp" => 3,
            ],
            "upg_black_22" => [
                "type" => "upg upg_black",
                "w" => 1,
                "h" => 2,
                "num" => 22,
                "t" => "black",
                "r" => "telescope,foodDis",
            ],
            "upg_green_31" => [
                "type" => "upg upg_green",
                "w" => 1,
                "h" => 1,
                "num" => 31,
                "t" => "green",
                "r" => "camel",
                "vp" => 1,
            ],
            "upg_green_32" => [
                "type" => "upg upg_green",
                "w" => 1,
                "h" => 1,
                "num" => 32,
                "t" => "green",
                "r" => "ship",
                "vp" => 1,
            ],
            "upg_green_33" => [
                "type" => "upg upg_green",
                "w" => 1,
                "h" => 1,
                "num" => 33,
                "t" => "green",
                "r" => "telescope",
                "vp" => 1,
            ],
            "upg_green_34" => [
                "type" => "upg upg_green",
                "w" => 1,
                "h" => 1,
                "num" => 34,
                "t" => "green",
                "r" => "pigeon",
                "vp" => 1,
            ],
            "upg_pink_40" => [
                "type" => "upg upg_pink",
                "w" => 1,
                "h" => 1,
                "num" => 40,
                "t" => "pink",
                "tags" => "Vista",
                "vp" => 1,
            ],
            "upg_pink_41" => [
                "type" => "upg upg_pink",
                "w" => 1,
                "h" => 1,
                "num" => 41,
                "t" => "pink",
                "tags" => "City",
                "vp" => 1,
            ],
            "upg_pink_42" => [
                "type" => "upg upg_pink",
                "w" => 1,
                "h" => 1,
                "num" => 42,
                "t" => "pink",
                "tags" => "Sea",
                "vp" => 1,
            ],
            "upg_pink_43" => [
                "type" => "upg upg_pink",
                "w" => 1,
                "h" => 1,
                "num" => 43,
                "t" => "pink",
                "tags" => "Harbour",
                "vp" => 1,
            ],
            "upg_pink_44" => [
                "type" => "upg upg_pink",
                "w" => 1,
                "h" => 1,
                "num" => 44,
                "t" => "pink",
                "tags" => "Observatory",
                "vp" => 5,
            ],
            "upg_pink_45" => [
                "type" => "upg upg_pink",
                "w" => 1,
                "h" => 1,
                "num" => 45,
                "t" => "pink",
                "tags" => "Book",
                "vp" => 5,
            ],
            "upg_pink_46" => [
                "type" => "upg upg_pink",
                "w" => 1,
                "h" => 1,
                "num" => 46,
                "t" => "pink",
                "tags" => "Planet",
                "vp" => 3,
            ],
            "upg_pink_47" => [
                "type" => "upg upg_pink",
                "w" => 1,
                "h" => 1,
                "num" => 47,
                "t" => "pink",
                "tags" => "Stars",
                "vp" => 5,
            ],
            "upg_pink_48" => [
                "type" => "upg upg_pink",
                "w" => 1,
                "h" => 1,
                "num" => 48,
                "t" => "pink",
                "tags" => "Comet Comet",
                "vp" => 4,
            ],
            "upg_pink_49" => [
                "type" => "upg upg_pink",
                "w" => 1,
                "h" => 1,
                "num" => 49,
                "t" => "pink",
                "tags" => "Comet",
                "vp" => 5,
            ],
            /* --- gen php end upg_material --- */
            /* --- gen php begin action_material --- */
            // # Land card worker actions (positions 1-4)
            "action_land_1" => [
                "type" => "action",
                "ctype" => "land",
                "num" => 1,
                "r" => "cardFolk,diceMod",
            ],
            "action_land_2" => [
                "type" => "action",
                "ctype" => "land",
                "num" => 2,
                "r" => "2coin,infYellow",
            ],
            "action_land_3" => [
                "type" => "action",
                "ctype" => "land",
                "num" => 3,
                "r" => "upgYellow",
            ],
            "action_land_4" => [
                "type" => "action",
                "ctype" => "land",
                "num" => 4,
                "r" => "3food,cardDraw(land)",
            ],
            // # Water card worker actions (positions 1-4)
            "action_water_1" => [
                "type" => "action",
                "ctype" => "water",
                "num" => 1,
                "r" => "reroll,diceMod,diceMod",
            ],
            "action_water_2" => [
                "type" => "action",
                "ctype" => "water",
                "num" => 2,
                "r" => "2food,infBlue",
            ],
            "action_water_3" => [
                "type" => "action",
                "ctype" => "water",
                "num" => 3,
                "r" => "upgBlue",
            ],
            "action_water_4" => [
                "type" => "action",
                "ctype" => "water",
                "num" => 4,
                "r" => "3food,cardDraw(water)",
            ],
            // # Folk card worker actions (positions 1-4)
            "action_folk_1" => [
                "type" => "action",
                "ctype" => "folk",
                "num" => 1,
                "r" => "cardSpace(dis)",
            ],
            "action_folk_2" => [
                "type" => "action",
                "ctype" => "folk",
                "num" => 2,
                "r" => "infYellow,infBlue,infBlack",
            ],
            "action_folk_3" => [
                "type" => "action",
                "ctype" => "folk",
                "num" => 3,
                "r" => "upgGreen(free)",
            ],
            "action_folk_4" => [
                "type" => "action",
                "ctype" => "folk",
                "num" => 4,
                "r" => "journal,food",
            ],
            // # Inspiration card worker actions (positions 1-4)
            "action_insp_1" => [
                "type" => "action",
                "ctype" => "insp",
                "num" => 1,
                "r" => "2food",
            ],
            "action_insp_2" => [
                "type" => "action",
                "ctype" => "insp",
                "num" => 2,
                "r" => "food,infAny",
            ],
            "action_insp_3" => [
                "type" => "action",
                "ctype" => "insp",
                "num" => 3,
                "r" => "coin,reroll",
            ],
            "action_insp_4" => [
                "type" => "action",
                "ctype" => "insp",
                "num" => 4,
                "r" => "2coin",
            ],
            /* --- gen php end action_material --- */

            /* --- gen php begin cardspace_material --- */
// # Space cards (77-113)
    "card_space_77" => [ 
        "create" => 1,
        "num" => 77,
        "r" => "journal",
        "vpexp" => "win_Comet?4:3",
        "tags" => "Comet",
        "tor" => "Journal",
        "tovp" => "If you have more Comet tags than each opponent: 4 VP, otherwise 3 VP",
],
    "card_space_78" => [ 
        "create" => 1,
        "num" => 78,
        "r" => "journal",
        "vpexp" => "win_Comet?4:3",
        "tags" => "Comet",
        "tor" => "Journal",
        "tovp" => "If you have more Comet tags than each opponent: 4 VP, otherwise 3 VP",
],
    "card_space_79" => [ 
        "create" => 1,
        "num" => 79,
        "r" => "reroll",
        "vpexp" => "win_Comet?4:2",
        "tags" => "Comet Comet",
        "tor" => "Refresh a Die",
        "tovp" => "If you have more Comet tags than each opponent: 4 VP, otherwise 2 VP",
],
    "card_space_80" => [ 
        "create" => 1,
        "num" => 80,
        "r" => "reroll",
        "vpexp" => "win_Comet?4:2",
        "tags" => "Comet Comet",
        "tor" => "Refresh a Die",
        "tovp" => "If you have more Comet tags than each opponent: 4 VP, otherwise 2 VP",
],
    "card_space_81" => [ 
        "create" => 1,
        "num" => 81,
        "r" => "reroll",
        "vpexp" => "win_Comet?4:2",
        "tags" => "Comet Comet",
        "tor" => "Refresh a Die",
        "tovp" => "If you have more Comet tags than each opponent: 4 VP, otherwise 2 VP",
],
    "card_space_82" => [ 
        "create" => 1,
        "num" => 82,
        "vpexp" => "win_Comet?4:1",
        "tags" => "Comet Comet Comet",
        "tovp" => "If you have more Comet tags than each opponent: 4 VP, otherwise 1 VP",
],
    "card_space_83" => [ 
        "create" => 1,
        "num" => 83,
        "vpexp" => "win_Comet?4:1",
        "tags" => "Comet Comet Comet",
        "tovp" => "If you have more Comet tags than each opponent: 4 VP, otherwise 1 VP",
],
    "card_space_84" => [ 
        "create" => 1,
        "num" => 84,
        "vpexp" => "win_Comet?4:1",
        "tags" => "Comet Comet Comet",
        "tovp" => "If you have more Comet tags than each opponent: 4 VP, otherwise 1 VP",
],
    "card_space_85" => [ 
        "create" => 1,
        "num" => 85,
        "r" => "infBlue",
        "vpexp" => "tag_Sun?7:3",
        "tags" => "Moon",
        "tor" => "Place influence on Blue Guild",
        "tovp" => "If you have a Sun tag: 7 VP, otherwise 3 VP",
],
    "card_space_86" => [ 
        "create" => 1,
        "num" => 86,
        "r" => "infYellow",
        "vpexp" => "1+tag_Planet",
        "tags" => "Planet",
        "tor" => "Place influence on Yellow Guild",
        "tovp" => "1 VP + 1 VP per Planet tag",
],
    "card_space_87" => [ 
        "create" => 1,
        "num" => 87,
        "r" => "food",
        "vpexp" => "1+tag_Planet",
        "tags" => "Planet",
        "tor" => "Gain provisions",
        "tovp" => "1 VP + 1 VP per Planet tag",
],
    "card_space_88" => [ 
        "create" => 1,
        "num" => 88,
        "r" => "infCard",
        "vpexp" => "1+tag_Planet",
        "tags" => "Stars",
        "tor" => "Acquire inspiration card",
        "tovp" => "1 VP + 1 VP per Planet tag",
],
    "card_space_89" => [ 
        "create" => 1,
        "num" => 89,
        "r" => "infBlack",
        "vpexp" => "1+tag_Planet",
        "tags" => "Stars",
        "tor" => "Place influence on Black Guild",
        "tovp" => "1 VP + 1 VP per Planet tag",
],
    "card_space_90" => [ 
        "create" => 1,
        "num" => 90,
        "r" => "infBlue",
        "vpexp" => "1+tag_Planet",
        "tags" => "Stars",
        "tor" => "Place influence on Blue Guild",
        "tovp" => "1 VP + 1 VP per Planet tag",
],
    "card_space_91" => [ 
        "create" => 1,
        "num" => 91,
        "r" => "infCard",
        "vpexp" => "min(tag_Planet,tag_Comet,tag_Stars)*3",
        "tags" => "Stars",
        "tor" => "Acquire inspiration card",
        "tovp" => "3 VP per set of Planet, Comet, and Stars tags",
],
    "card_space_92" => [ 
        "create" => 1,
        "num" => 92,
        "vpexp" => "tag_City",
        "tags" => "Stars",
        "tovp" => "1 VP per City tag",
],
    "card_space_93" => [ 
        "create" => 1,
        "num" => 93,
        "vpexp" => "tag_City",
        "tags" => "Stars",
        "tovp" => "1 VP per City tag",
],
    "card_space_94" => [ 
        "create" => 1,
        "num" => 94,
        "vpexp" => "tag_Harbour",
        "tags" => "Stars",
        "tovp" => "1 VP per Harbour tag",
],
    "card_space_95" => [ 
        "create" => 1,
        "num" => 95,
        "vpexp" => "tag_Harbour",
        "tags" => "Stars",
        "tovp" => "1 VP per Harbour tag",
],
    "card_space_96" => [ 
        "create" => 1,
        "num" => 96,
        "r" => "cardInsp",
        "vpexp" => "card_insp",
        "tags" => "Stars",
        "tor" => "Acquire inspiration card",
        "tovp" => "1 VP per Inspiration card",
],
    "card_space_97" => [ 
        "create" => 1,
        "num" => 97,
        "r" => "infBlack,infMove",
        "vpexp" => "1+inf_black/2",
        "tags" => "Stars",
        "tor" => "Place influence on Black Guild, then move any influence",
        "tovp" => "1 VP + 1 VP per 2 influence on Black Guild",
],
    "card_space_98" => [ 
        "create" => 1,
        "num" => 98,
        "r" => "infBlue,infMove",
        "vpexp" => "1+inf_blue/2",
        "tags" => "Stars",
        "tor" => "Place influence on Blue Guild, then move any influence",
        "tovp" => "1 VP + 1 VP per 2 influence on Blue Guild",
],
    "card_space_99" => [ 
        "create" => 1,
        "num" => 99,
        "r" => "infYellow,infMove",
        "vpexp" => "1+inf_yellow/2",
        "tags" => "Stars",
        "tor" => "Place influence on Yellow Guild, then move any influence",
        "tovp" => "1 VP + 1 VP per 2 influence on Yellow Guild",
],
    "card_space_100" => [ 
        "create" => 1,
        "num" => 100,
        "r" => "food",
        "vpexp" => "1+tag_Book",
        "tags" => "Stars",
        "tor" => "Gain provisions",
        "tovp" => "1 VP + 1 VP per Book tag",
],
    "card_space_101" => [ 
        "create" => 1,
        "num" => 101,
        "r" => "food",
        "vpexp" => "1+tag_Observatory",
        "tags" => "Stars",
        "tor" => "Gain provisions",
        "tovp" => "1 VP + 1 VP per Observatory tag",
],
    "card_space_102" => [ 
        "create" => 1,
        "num" => 102,
        "vpexp" => "tag_Sea",
        "tags" => "Stars",
        "tovp" => "1 VP per Open Water tag",
],
    "card_space_103" => [ 
        "create" => 1,
        "num" => 103,
        "vpexp" => "tag_Sea",
        "tags" => "Stars",
        "tovp" => "1 VP per Open Water tag",
],
    "card_space_104" => [ 
        "create" => 1,
        "num" => 104,
        "r" => "cardFolk(free)",
        "vpexp" => "min(card_folk,card_space,card_land,card_water)",
        "tags" => "Stars",
        "tor" => "Acquire Townsfolk card (free)",
        "tovp" => "1 VP per set of Townsfolk, Space, Land, and Water cards",
],
    "card_space_105" => [ 
        "create" => 1,
        "num" => 105,
        "r" => "infCard",
        "vpexp" => "tag_Stars",
        "tags" => "Stars",
        "tor" => "Acquire inspiration card",
        "tovp" => "1 VP per Stars tag",
],
    "card_space_106" => [ 
        "create" => 1,
        "num" => 106,
        "r" => "infBlack",
        "vpexp" => "1+upg_black",
        "tags" => "Stars",
        "tor" => "Place influence on Black Guild",
        "tovp" => "1 VP + 1 VP per Space upgrade tile",
],
    "card_space_107" => [ 
        "create" => 1,
        "num" => 107,
        "r" => "infBlue",
        "vpexp" => "1+upg_blue",
        "tags" => "Stars",
        "tor" => "Place influence on Blue Guild",
        "tovp" => "1 VP + 1 VP per Water upgrade tile",
],
    "card_space_108" => [ 
        "create" => 1,
        "num" => 108,
        "r" => "cardFolk(free)",
        "vpexp" => "1+upg_green",
        "tags" => "Stars",
        "tor" => "Acquire Townsfolk card (free)",
        "tovp" => "1 VP + 1 VP per Basic upgrade tile",
],
    "card_space_109" => [ 
        "create" => 1,
        "num" => 109,
        "r" => "infYellow",
        "vpexp" => "1+upg_yellow",
        "tags" => "Stars",
        "tor" => "Place influence on Yellow Guild",
        "tovp" => "1 VP + 1 VP per Land upgrade tile",
],
    "card_space_110" => [ 
        "create" => 1,
        "num" => 110,
        "vpexp" => "tag_Vista",
        "tags" => "Stars",
        "tovp" => "1 VP per Vista tag",
],
    "card_space_111" => [ 
        "create" => 1,
        "num" => 111,
        "vpexp" => "tag_Vista",
        "tags" => "Stars",
        "tovp" => "1 VP per Vista tag",
],
    "card_space_112" => [ 
        "create" => 1,
        "num" => 112,
        "vpexp" => "tag_Moon?7:3",
        "tags" => "Sun",
        "tovp" => "If you have a Moon tag: 7 VP, otherwise 3 VP",
],
    "card_space_113" => [ 
        "create" => 1,
        "ext" => 1,
        "num" => 113,
        "r" => "upgPink",
        "vpexp" => 1,
        "tags" => "Comet",
        "tor" => "Gain special upgrade tile",
        "tovp" => "1 VP",
],
// # Home card
    "card_space_1" => [ 
        "create" => 0,
        "num" => 1,
        "vpexp" => "min(upg_green,card_folk)",
        "tags" => "Stars",
        "tovp" => "1 VP per set of Basic upgrade and Townsfolk",
],
            /* --- gen php end cardspace_material --- */

            /* --- gen php begin cardinsp_material --- */
            // # Inspiration cards (1-18)
            "card_insp_1" => [
                "create" => 1,
                "num" => 1,
                "collect" => "tag_Comet",
                "goal" => 6,
                "tooltip" => clienttranslate("Have at least 6 Comet tags"),
            ],
            "card_insp_2" => [
                "create" => 1,
                "num" => 2,
                "collect" => "tag_Stars",
                "goal" => 5,
                "tooltip" => clienttranslate("Have at least 5 Stars tags, including starting tag"),
            ],
            "card_insp_3" => [
                "create" => 1,
                "num" => 3,
                "collect" => "tag_Planet",
                "goal" => 3,
                "tooltip" => clienttranslate("Have at least 3 Planet tags"),
            ],
            "card_insp_4" => [
                "create" => 1,
                "num" => 4,
                "collect" => "card_folk",
                "goal" => 6,
                "tooltip" => clienttranslate("Have at least 6 Townsfolk cards, including starting card"),
            ],
            "card_insp_5" => [
                "create" => 1,
                "num" => 5,
                "collect" => "tag_Library",
                "goal" => 4,
                "tooltip" => clienttranslate("Have at least 4 Library tags, including starting tag"),
            ],
            "card_insp_6" => [
                "create" => 1,
                "num" => 6,
                "collect" => "tag_Vista",
                "goal" => 4,
                "tooltip" => clienttranslate("Have at least 4 Vista tags"),
            ],
            "card_insp_7" => [
                "create" => 1,
                "num" => 7,
                "collect" => "tag_Sea",
                "goal" => 4,
                "tooltip" => clienttranslate("Have at least 4 Open Water tags"),
            ],
            "card_insp_8" => [
                "create" => 1,
                "num" => 8,
                "collect" => "tag_Harbour",
                "goal" => 5,
                "tooltip" => clienttranslate("Have at least 5 Harbour tags, including starting tag"),
            ],
            "card_insp_9" => [
                "create" => 1,
                "num" => 9,
                "collect" => "min(upg_green,upg_black)",
                "goal" => 2,
                "tooltip" => clienttranslate("Have at least two Basic upgrades and two Space upgrades"),
            ],
            "card_insp_10" => [
                "create" => 1,
                "num" => 10,
                "collect" => "upg_blue",
                "goal" => 3,
                "tooltip" => clienttranslate("Have at least 3 Water upgrades"),
            ],
            "card_insp_11" => [
                "create" => 1,
                "num" => 11,
                "collect" => "upg_yellow",
                "goal" => 3,
                "tooltip" => clienttranslate("Have at least 3 Land upgrades"),
            ],
            "card_insp_12" => [
                "create" => 1,
                "num" => 12,
                "collect" => "inf_yellow+inf_blue+inf_black",
                "goal" => 10,
                "tooltip" => clienttranslate("Have at least 10 combined influence in all guilds"),
            ],
            "card_insp_13" => [
                "create" => 1,
                "num" => 13,
                "collect" => "tag_Observatory",
                "goal" => 4,
                "tooltip" => clienttranslate("Have at least 4 Observatory tags, including starting tag"),
            ],
            "card_insp_14" => [
                "create" => 1,
                "num" => 14,
                "collect" => "tag_City",
                "goal" => 5,
                "tooltip" => clienttranslate("Have at least 5 City tags, including starting tag"),
            ],
            "card_insp_15" => [
                "create" => 1,
                "num" => 15,
                "collect" => "tracker_food",
                "goal" => 6,
                "tooltip" => clienttranslate("Have at least 6 Provisions"),
            ],
            "card_insp_15" => [
                "create" => 1,
                "num" => 15,
                "collect" => "tracker_coin",
                "goal" => 6,
                "tooltip" => clienttranslate("Have at least 6 Silver"),
            ],
            "card_insp_17" => [
                "create" => 1,
                "num" => 17,
                "collect" => "card_land",
                "goal" => 8,
                "tooltip" => clienttranslate("Have at least 8 Land cards, including starting card"),
            ],
            "card_insp_18" => [
                "create" => 1,
                "num" => 18,
                "collect" => "card_water",
                "goal" => 8,
                "tooltip" => clienttranslate("Have at least 8 Water cards, including starting card"),
            ],
            /* --- gen php end cardinsp_material --- */
        ];
    }

    public function get(): array {
        return $this->token_types;
    }

    /**
     * This has to be called from "initTable" method of game which is when db is conected but action is not started yet
     */
    public function adjustMaterial(Game $game) {
        if ($this->adjusted) {
            return $this->token_types;
        }
        $this->adjusted = true;
        // ... do something reading number or palyer of game options with material

        return $this->token_types;
    }

    function getRulesFor($token_id, $field = "r", $default = "") {
        $tt = $this->token_types;
        $key = $token_id;
        while ($key) {
            $data = $tt[$key] ?? null;
            if ($data) {
                if ($field === "*") {
                    $data["_key"] = $key;
                    return $data;
                }
                $value = $data[$field] ?? null;
                if ($value !== null) {
                    return $value;
                }
            }
            $new_key = $this->getPartsPrefix($key, -1);
            if ($new_key == $key) {
                break;
            }
            $key = $new_key;
        }
        //$this->systemAssertTrue("bad token $token_id for rule $field", false);
        return $default;
    }

    /** Find stuff in material file */
    function find(string $field, ?string $value, bool $ignorecase = true) {
        foreach ($this->token_types as $key => $rules) {
            $cur = $rules[$field] ?? null;
            if ($cur == $value) {
                return $key;
            }
            if ($ignorecase && is_string($cur) && strcasecmp($cur, $value) == 0) {
                return $key;
            }
        }
        return null;
    }
    function findByName(string $value, bool $ignorecase = true) {
        return $this->find("name", $value, $ignorecase);
    }

    /**
     * Return $i parts of string (part is chunk separated by _
     * I.e.
     * getPartsPrefix("a_b_c",2)=="a_b"
     *
     * If $i is negative - it will means how much remove from tail, i.e
     * getPartsPrefix("a_b_c",-1)=="a_b"
     */
    static function getPartsPrefix($haystack, $i) {
        $parts = explode("_", $haystack);
        $len = count($parts);
        if ($i < 0) {
            $i = $len + $i;
        }
        if ($i <= 0) {
            return "";
        }
        for (; $i < $len; $i++) {
            unset($parts[$i]);
        }
        return implode("_", $parts);
    }

    /**
     * Set rules for a token (used for testing)
     */
    function setRulesFor(string $token_id, array $rules): void {
        if (!isset($this->token_types[$token_id])) {
            $this->token_types[$token_id] = [];
        }
        $this->token_types[$token_id] = array_merge($this->token_types[$token_id], $rules);
    }
}
