<?php

declare(strict_types=1);

namespace Bga\Games\wayfarers;

class Material {
    const RET_OK = 0;
    const ERR_COST = 1;
    const ERR_PREREQ = 2;
    const ERR_OCCUPIED = 3;
    const ERR_MAX = 4;
    const ERR_NONE_LEFT = 5;
    const ERR_NOT_APPLICABLE = 6;

    private array $token_types;
    private bool $adjusted = false;
    public function __construct() {
        $this->token_types = [
            // #error codes - MANUAL ENTRY
            "err_0" => [
                //
                "code" => Material::RET_OK,
                "type" => "err",
                "name" => clienttranslate("Ok"),
            ],
            "err_1" => [
                //
                "code" => Material::ERR_COST,
                "type" => "err",
                "name" => clienttranslate("Insufficient Resources"),
            ],

            "err_2" => [
                //
                "code" => Material::ERR_PREREQ,
                "type" => "err",
                "name" => clienttranslate("Prerequisites are not fullfilled"),
            ],
            "err_3" => [
                //
                "code" => Material::ERR_OCCUPIED,
                "type" => "err",
                "name" => clienttranslate("Location is occupied"),
            ],
            "err_4" => [
                //
                "code" => Material::ERR_MAX,
                "type" => "err",
                "name" => clienttranslate("Maximum capacity is reached"),
            ],
            "err_5" => [
                //
                "code" => Material::ERR_NONE_LEFT,
                "type" => "err",
                "name" => clienttranslate("None left"),
            ],

            "err_6" => [
                //
                "code" => Material::ERR_NOT_APPLICABLE,
                "type" => "err",
                "name" => clienttranslate("Not applicable"),
            ],

            /* --- gen php begin loc_material --- */
    "deck_folk" => [ 
        "type" => "location",
        "showtooltip" => 0,
        "create" => 0,
        "name" => clienttranslate("Townfolk Cards"),
        "location" => "supply",
        "scope" => "global",
        "counter" => "public",
        "content" => "hidden",
],
    "deck_land" => [ 
        "type" => "location",
        "showtooltip" => 0,
        "create" => 0,
        "name" => clienttranslate("Land Cards"),
        "location" => "supply",
        "scope" => "global",
        "counter" => "public",
        "content" => "hidden",
],
    "deck_water" => [ 
        "type" => "location",
        "showtooltip" => 0,
        "create" => 0,
        "name" => clienttranslate("Water Cards"),
        "location" => "supply",
        "scope" => "global",
        "counter" => "public",
        "content" => "hidden",
],
    "deck_space" => [ 
        "type" => "location",
        "showtooltip" => 0,
        "create" => 0,
        "name" => clienttranslate("Space Cards"),
        "location" => "supply",
        "scope" => "global",
        "counter" => "public",
        "content" => "hidden",
],
    "deck_insp" => [ 
        "type" => "location",
        "showtooltip" => 0,
        "create" => 0,
        "name" => clienttranslate("Inspiration Cards"),
        "location" => "supply",
        "scope" => "global",
        "counter" => "public",
        "content" => "hidden",
],
    "limbo" => [ 
        "type" => "location",
        "showtooltip" => 0,
        "create" => 0,
        "name" => clienttranslate("Limbo"),
        "scope" => "global",
        "counter" => "hidden",
        "content" => "hidden",
],
    "tableau" => [ 
        "type" => "location",
        "showtooltip" => 0,
        "create" => 0,
        "name" => clienttranslate("Player Area"),
        "location" => "players_panels",
        "scope" => "player",
        "counter" => "hidden",
        "content" => "public",
],
    "hand" => [ 
        "type" => "location",
        "showtooltip" => 0,
        "create" => 0,
        "name" => clienttranslate("Player Hand"),
        "location" => "players_panels",
        "scope" => "player",
        "counter" => "hidden",
        "content" => "private",
],
    "supply" => [ 
        "type" => "location",
        "showtooltip" => 0,
        "create" => 0,
        "name" => clienttranslate("Supply"),
        "location" => "supply",
        "scope" => "global",
        "counter" => "public",
        "content" => "public",
],
    "guild_black" => [ 
        "type" => "location",
        "showtooltip" => 0,
        "create" => 0,
        "name" => clienttranslate("Black Guild (Science)"),
        "location" => "mainarea",
        "scope" => "global",
        "counter" => "hidden",
        "content" => "public",
],
    "guild_blue" => [ 
        "type" => "location",
        "showtooltip" => 0,
        "create" => 0,
        "name" => clienttranslate("Blue Guild (Exploration)"),
        "location" => "mainarea",
        "scope" => "global",
        "counter" => "hidden",
        "content" => "public",
],
    "guild_yellow" => [ 
        "type" => "location",
        "showtooltip" => 0,
        "create" => 0,
        "name" => clienttranslate("Yellow Guild (Trade)"),
        "location" => "mainarea",
        "scope" => "global",
        "counter" => "hidden",
        "content" => "public",
],
            /* --- gen php end loc_material --- */
            /* --- gen php begin op_material --- */
    "Op_nop" => [ 
        "type" => "nop",
        "name" => clienttranslate("None"),
],
// #fake name
    "Op_barrier" => [ 
        "type" => "barrier",
        "name" => clienttranslate("None"),
],
    "Op_savepoint" => [ 
        "type" => "savepoint",
        "name" => clienttranslate("None"),
],
    "Op_or" => [ 
        "type" => "or",
        "name" => clienttranslate("Choice"),
],
    "Op_unique" => [ 
        "type" => "unique",
        "name" => clienttranslate("Unique Choice"),
],
    "Op_order" => [ 
        "type" => "order",
        "name" => clienttranslate("Choose Order"),
],
    "Op_seq" => [ 
        "type" => "seq",
        "name" => clienttranslate("Sequence"),
],
    "Op_gain" => [ 
        "type" => "gain",
        "name" => clienttranslate("Gain"),
],
    "Op_pay" => [ 
        "type" => "pay",
        "name" => clienttranslate("Pay"),
],
    "Op_paygain" => [ 
        "type" => "paygain",
        "name" => clienttranslate("Trade"),
],
    "Op_turn" => [ 
        "type" => "turn",
        "name" => clienttranslate("Turn"),
],
    "Op_rest" => [ 
        "type" => "rest",
        "name" => clienttranslate("Rest"),
],
    "Op_placeWorker" => [ 
        "type" => "placeWorker",
        "name" => clienttranslate("Place Worker"),
],
    "Op_cardSpace" => [ 
        "type" => "cardSpace",
        "name" => clienttranslate("Gain Space Card"),
],
    "Op_cardFolk" => [ 
        "type" => "cardFolk",
        "name" => clienttranslate("Gain Townfolk Card"),
],
    "Op_cardWater" => [ 
        "type" => "cardWater",
        "name" => clienttranslate("Gain Water Card"),
],
    "Op_cardLand" => [ 
        "type" => "cardLand",
        "name" => clienttranslate("Gain Land Card"),
],
    "Op_upgBlack" => [ 
        "type" => "upgBlack",
        "name" => clienttranslate("Gain Black Upgrade"),
],
    "Op_upgBlue" => [ 
        "type" => "upgBlue",
        "name" => clienttranslate("Gain Blue Upgrade"),
],
    "Op_upgGreen" => [ 
        "type" => "upgGreen",
        "name" => clienttranslate("Gain Green Upgrade"),
],
    "Op_upgPink" => [ 
        "type" => "upgPink",
        "name" => clienttranslate("Gain Pink Upgrade"),
],
    "Op_upgYellow" => [ 
        "type" => "upgYellow",
        "name" => clienttranslate("Gain Yellow Upgrade"),
],
    "Op_journal" => [ 
        "type" => "journal",
        "name" => clienttranslate("Journal"),
],
    "Op_pickWorker" => [ 
        "type" => "pickWorker",
        "name" => clienttranslate("Pick a Worker"),
],
    "Op_drawTab" => [ 
        "type" => "drawTab",
        "name" => clienttranslate("Refill Cards"),
],
    "Op_reroll" => [ 
        "type" => "reroll",
        "name" => clienttranslate("Re-roll"),
],
    "Op_ship" => [ 
        "type" => "ship",
        "name" => clienttranslate("Ship"),
],
    "Op_camel" => [ 
        "type" => "camel",
        "name" => clienttranslate("Camel"),
],
    "Op_telescope" => [ 
        "type" => "telescope",
        "name" => clienttranslate("Telescope"),
],
    "Op_bird" => [ 
        "type" => "bird",
        "name" => clienttranslate("Bird"),
],
    "Op_infAny" => [ 
        "type" => "infAny",
        "name" => clienttranslate("Influence on any Guild"),
],
    "Op_infBlue" => [ 
        "type" => "infBlue",
        "name" => clienttranslate("Influence on Blue"),
],
    "Op_infYellow" => [ 
        "type" => "infYellow",
        "name" => clienttranslate("Influence on Yellow"),
],
    "Op_infBlack" => [ 
        "type" => "infBlack",
        "name" => clienttranslate("Influence on Black"),
],
    "Op_infCard" => [ 
        "type" => "infCard",
        "name" => clienttranslate("Influence on Card"),
],
    "Op_infMove" => [ 
        "type" => "infMove",
        "name" => clienttranslate("Move Influence"),
],
    "Op_diceMod" => [ 
        "type" => "diceMod",
        "name" => clienttranslate("Modify Dice by +/- 1"),
],
    "Op_dicePlus" => [ 
        "type" => "dicePlus",
        "name" => clienttranslate("Modify Dice by +1"),
],
    "Op_diceMinus" => [ 
        "type" => "diceMinus",
        "name" => clienttranslate("Modify Dice by -1"),
],
    "Op_food" => [ 
        "class" => "Op_gain",
        "type" => "food",
        "name" => clienttranslate("Gain Provisions"),
],
    "Op_coin" => [ 
        "class" => "Op_gain",
        "type" => "coin",
        "name" => clienttranslate("Gain Silver"),
],
    "Op_n_food" => [ 
        "class" => "Op_pay",
        "type" => "n_food",
        "name" => clienttranslate("Pay Provisions"),
],
    "Op_n_coin" => [ 
        "class" => "Op_pay",
        "type" => "n_coin",
        "name" => clienttranslate("Pay Silver"),
],
            /* --- gen php end op_material --- */
            /* --- gen php begin token_material --- */
// # create is one of the numbers
// # 0 - do not create token
// # 1 - the token with id $id will be created, count must be set to 1 if used
// # 2 - the token with id "${id}_{INDEX}" will be created, using count starting from 1
// # 3 - the token with id "${id}_{COLOR}_{INDEX}" will be created, using count, per player
// # 4 - the token with id "${id}_{COLOR}" for each player will be created, count must be 1
// # 5 - the token with id "${id}_{INDEX}_{COLOR}" for each player will be created
// # 6 - custom placeholders
// #12  Workers 4 of each 3 colors
    "worker_blue" => [ 
        "name" => clienttranslate("Blue Worker"),
        "count" => 4,
        "type" => "worker wooden",
        "create" => 2,
        "location" => "limbo",
],
    "worker_yellow" => [ 
        "name" => clienttranslate("Yellow Worker"),
        "count" => 4,
        "type" => "worker wooden",
        "create" => 2,
        "location" => "limbo",
],
    "worker_green" => [ 
        "name" => clienttranslate("Green Worker"),
        "count" => 4,
        "type" => "worker wooden",
        "create" => 2,
        "location" => "limbo",
],
// #player counters
    "tracker_coin" => [ 
        "name" => clienttranslate("Silver"),
        "count" => 1,
        "type" => "tracker coin",
        "create" => 4,
        "location" => "miniboard_{COLOR}",
],
    "tracker_food" => [ 
        "name" => clienttranslate("Provision"),
        "count" => 1,
        "type" => "tracker food",
        "create" => 4,
        "location" => "miniboard_{COLOR}",
],
    "marker" => [ 
        "name" => clienttranslate("Player marker"),
        "count" => 1,
        "type" => "marker wooden",
        "create" => 4,
        "location" => "tableau_{COLOR}",
],
    "influence" => [ 
        "name" => clienttranslate("Influence"),
        "count" => 15,
        "type" => "influence wooden",
        "create" => 3,
        "location" => "tableau_{COLOR}",
],
    "dice" => [ 
        "name" => clienttranslate("Player dice"),
        "count" => 5,
        "type" => "dice wooden",
        "create" => 3,
        "location" => "tableau_{COLOR}",
],
// #journal tiles
    "jtile" => [ 
        "name" => clienttranslate("Journal Tile"),
        "count" => 10,
        "type" => "jtile tile",
        "create" => 2,
        "location" => "deck_jtile",
],
    "upg" => [ 
        "name" => clienttranslate("Upgrade Tile"),
        "count" => 10,
        "type" => "upg tile",
        "create" => 2,
        "location" => "supply",
],
// #cards
// #36 Townsfolk Cards 36 Space Cards 36 Land Cards 16 Inspiration Cards 36 Water Cards 6 Scheme Cards
// #create=0
// #card_folk|Townsfolk|36|card folk|2|deck_folk
// #create=1
    "card_space" => [ 
        "name" => clienttranslate("Space"),
        "count" => 36,
        "type" => "card space",
        "create" => 2,
        "location" => "deck_space",
],
// #card_land|Land|36|card land|2|deck_land
    "card_water" => [ 
        "name" => clienttranslate("Water"),
        "count" => 36,
        "type" => "card water",
        "create" => 2,
        "location" => "deck_water",
],
    "card_insp" => [ 
        "name" => clienttranslate("Inspiration"),
        "count" => 16,
        "type" => "card insp",
        "create" => 2,
        "location" => "deck_insp",
],
// #boards
    "mainboard_1" => [ 
        "count" => 1,
        "type" => "mainboard_x left",
        "create" => 1,
        "location" => "mainboardall",
],
    "mainboard_2" => [ 
        "count" => 1,
        "type" => "mainboard_x middle",
        "create" => 1,
        "location" => "mainboardall",
],
    "mainboard_3" => [ 
        "count" => 1,
        "type" => "mainboard_x right",
        "create" => 1,
        "location" => "mainboardall",
],
    "game_stage" => [ 
        "count" => 1,
        "type" => "stage",
        "create" => 1,
        "location" => "limbo",
],
// #names of the stats
    "game_vp_tags" => [ 
        "create" => 0,
        "name" => clienttranslate("VP from Primary Tags (City, Vista, Harbour, Water)"),
],
    "game_vp_sets" => [ 
        "create" => 0,
        "name" => clienttranslate("VP from Tag Sets"),
],
    "game_vp_space" => [ 
        "create" => 0,
        "name" => clienttranslate("VP from Space Cards"),
],
    "game_vp_inspiration" => [ 
        "create" => 0,
        "name" => clienttranslate("VP from Inspiration Cards"),
],
    "game_vp_caravan" => [ 
        "create" => 0,
        "name" => clienttranslate("VP from Caravan Upgrade Tiles"),
],
    "game_vp_guilds" => [ 
        "create" => 0,
        "name" => clienttranslate("VP from Guild Majorities"),
],
    "game_vp_total" => [ 
        "create" => 0,
        "name" => clienttranslate("VP total"),
],
            /* --- gen php end token_material --- */

            /* --- gen php begin card_material --- */
    "card_home_1" => [ 
        "create" => 4,
        "t" => "home",
        "type" => "card card_home",
        "location" => "tableau_{COLOR}",
        "num" => 1,
        "tags" => "Book Observatory",
],
    "card_home_2" => [ 
        "create" => 4,
        "t" => "home",
        "type" => "card card_home",
        "location" => "tableau_{COLOR}",
        "num" => 2,
        "d" => "camel",
        "dr" => "cardLand,coin",
        "tags" => "City",
        "name" => clienttranslate("Capital City"),
],
    "card_home_3" => [ 
        "create" => 4,
        "t" => "home",
        "type" => "card card_home",
        "location" => "tableau_{COLOR}",
        "num" => 3,
        "d" => "ship",
        "dr" => "cardWater",
        "tags" => "Harbour",
        "name" => clienttranslate("Capital Harbour"),
],
    "card_home_10" => [ 
        "create" => 4,
        "t" => "home",
        "type" => "card card_home card_slot",
        "location" => "tableau_{COLOR}",
        "num" => 10,
        "d" => "telescope",
        "dr" => "(cardSpace/upgBlack)",
        "name" => clienttranslate("Capital Observatory"),
],
    "card_home_11" => [ 
        "create" => 4,
        "t" => "home",
        "type" => "card card_home card_slot",
        "location" => "tableau_{COLOR}",
        "num" => 11,
        "d" => "bird",
        "dr" => "(journal/(pickWorker,infAny))",
        "name" => clienttranslate("Capital Library"),
],
    "card_home_12" => [ 
        "create" => 4,
        "t" => "home",
        "type" => "card card_home card_slot",
        "location" => "tableau_{COLOR}",
        "num" => 12,
        "d" => "any",
        "dr" => "(cardFolk/2food)",
        "name" => clienttranslate("Capital Market"),
],
    "card_home_13" => [ 
        "create" => 4,
        "t" => "home",
        "type" => "card card_home card_slot",
        "location" => "tableau_{COLOR}",
        "num" => 13,
        "d" => "any",
        "dr" => "(upgGreen/2coin)",
        "name" => clienttranslate("Capital Reserve"),
],
    "card_folk_1" => [ 
        "create" => 4,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "tableau_{COLOR}",
        "rest" => 1,
        "num" => 1,
        "r" => 0,
        "dr" => "journal,coin",
        "name" => clienttranslate("Townfolk"),
],
    "card_folk_114" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 114,
        "r" => 1,
        "d" => "*",
        "dr" => "(coin/food):(pickWorker,reroll)",
        "tags" => "Vista",
        "name" => clienttranslate("Protector"),
],
    "card_folk_115" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 115,
        "r" => 2,
        "d" => "*",
        "dr" => "food:2coin",
        "tags" => "Observatory",
        "name" => clienttranslate("Wanderer"),
],
    "card_folk_116" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 116,
        "r" => 1,
        "dr" => "ship",
        "tags" => "Harbour",
        "name" => clienttranslate("Adventurer"),
],
    "card_folk_117" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 117,
        "r" => 0,
        "dr" => "telescope",
        "tags" => "Observatory",
        "name" => clienttranslate("Astronomer"),
],
    "card_folk_118" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 118,
        "r" => 2,
        "dr" => "pickWorker/infCard",
        "tags" => "Vista",
        "name" => clienttranslate("Champion"),
],
    "card_folk_121" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 121,
        "r" => 2,
        "dr" => "camel,bird",
        "tags" => "City",
        "name" => clienttranslate("Envoy"),
],
    "card_folk_122" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 122,
        "r" => 2,
        "dr" => "ship,bird",
        "tags" => "City",
        "name" => clienttranslate("Envoy"),
],
    "card_folk_123" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 123,
        "r" => 2,
        "dr" => "coin",
        "tags" => "City",
        "name" => clienttranslate("Farmer"),
],
    "card_folk_124" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 124,
        "r" => 2,
        "dr" => "food",
        "tags" => "City",
        "name" => clienttranslate("Farmer"),
],
    "card_folk_125" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 125,
        "r" => 2,
        "dr" => "coin",
        "tags" => "Harbour",
        "name" => clienttranslate("Fisherman"),
],
    "card_folk_126" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 126,
        "r" => 2,
        "dr" => "food",
        "tags" => "Harbour",
        "name" => clienttranslate("Fisherman"),
],
    "card_folk_130" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 130,
        "r" => 0,
        "dr" => "2diceMod",
        "tags" => "Vista",
        "name" => clienttranslate("Hunter"),
],
    "card_folk_131" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 131,
        "r" => 2,
        "dr" => "2ship",
        "tags" => "Harbour",
        "name" => clienttranslate("Invader"),
],
    "card_folk_132" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 132,
        "r" => 2,
        "dr" => "pickWorker/infCard",
        "tags" => "City Harbour",
        "name" => clienttranslate("Mercenary"),
],
    "card_folk_133" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 133,
        "r" => 2,
        "dr" => "coin",
        "tags" => "Vista",
        "name" => clienttranslate("Merchant"),
],
    "card_folk_134" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 134,
        "r" => 2,
        "dr" => "coin",
        "tags" => "Vista",
        "name" => clienttranslate("Merchant"),
],
    "card_folk_135" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 135,
        "r" => 2,
        "dr" => "food",
        "tags" => "Vista",
        "name" => clienttranslate("Merchant"),
],
    "card_folk_136" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 136,
        "r" => 2,
        "dr" => "food",
        "tags" => "Vista",
        "name" => clienttranslate("Merchant"),
],
    "card_folk_137" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 137,
        "r" => 1,
        "dr" => "bird",
        "tags" => "City Harbour",
        "name" => clienttranslate("Messenger"),
],
    "card_folk_138" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 138,
        "r" => 1,
        "dr" => "infCard/infMove/diceMod",
        "tags" => "City Harbour",
        "name" => clienttranslate("Rogue"),
],
    "card_folk_139" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 139,
        "r" => 1,
        "dr" => "infBlue/infMove",
        "tags" => "City Harbour",
        "name" => clienttranslate("Scholar"),
],
    "card_folk_140" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 140,
        "r" => 1,
        "dr" => "infYellow/infMove",
        "tags" => "City Harbour",
        "name" => clienttranslate("Scholar"),
],
    "card_folk_141" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 141,
        "r" => 2,
        "dr" => "infBlack/infMove",
        "tags" => "Book Observatory",
        "name" => clienttranslate("Scholar"),
],
    "card_folk_142" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 142,
        "r" => 1,
        "dr" => "infBlue/infMove",
        "tags" => "Book Observatory",
        "name" => clienttranslate("Scribe"),
],
    "card_folk_143" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 143,
        "r" => 1,
        "dr" => "infYellow/infMove",
        "tags" => "Book Observatory",
        "name" => clienttranslate("Scribe"),
],
    "card_folk_144" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 144,
        "r" => 2,
        "dr" => "infBlack/infMove",
        "tags" => "Vista",
        "name" => clienttranslate("Scribe"),
],
    "card_folk_145" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 145,
        "r" => 2,
        "dr" => "telescope,camel",
        "tags" => "City",
        "name" => clienttranslate("Stargazer"),
],
    "card_folk_149" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 149,
        "r" => 1,
        "dr" => "camel",
        "tags" => "City",
        "name" => clienttranslate("Vagrant"),
],
    "card_folk_150" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "num" => 150,
        "r" => 1,
        "dr" => "infCard/infMove/diceMod",
        "tags" => "Vista",
        "name" => clienttranslate("Vigilante"),
],
    "card_folk_119" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "rest" => 1,
        "num" => 119,
        "r" => 1,
        "dr" => "infMove,food",
        "tags" => "Water",
        "name" => clienttranslate("Enforcer"),
],
    "card_folk_120" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "rest" => 1,
        "num" => 120,
        "r" => 1,
        "dr" => "infMove,food",
        "tags" => "Water",
        "name" => clienttranslate("Enforcer"),
],
    "card_folk_127" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "rest" => 1,
        "num" => 127,
        "r" => 3,
        "dr" => "food,coin",
        "tags" => "Water",
        "name" => clienttranslate("Guardian"),
],
    "card_folk_128" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "rest" => 1,
        "num" => 128,
        "r" => 3,
        "dr" => "2coin",
        "tags" => "Water",
        "name" => clienttranslate("Guardian"),
],
    "card_folk_129" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "rest" => 1,
        "num" => 129,
        "r" => 3,
        "dr" => "2food",
        "tags" => "Water",
        "name" => clienttranslate("Guardian"),
],
    "card_folk_146" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "rest" => 1,
        "num" => 146,
        "r" => 1,
        "dr" => "infBlue/infMove",
        "tags" => "Water",
        "name" => clienttranslate("Translator"),
],
    "card_folk_147" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "rest" => 1,
        "num" => 147,
        "r" => 1,
        "dr" => "infYellow/infMove",
        "tags" => "Water",
        "name" => clienttranslate("Translator"),
],
    "card_folk_148" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "rest" => 1,
        "num" => 148,
        "r" => 2,
        "dr" => "infBlack/infMove",
        "tags" => "Water",
        "name" => clienttranslate("Translator"),
],
    "card_folk_151" => [ 
        "create" => 1,
        "t" => "folk",
        "type" => "card card_folk folk",
        "location" => "deck_folk",
        "rest" => 1,
        "num" => 151,
        "r" => 0,
        "dr" => "pickWorker/infMove",
        "tags" => "Water",
        "name" => clienttranslate("Warrior"),
],
            /* --- gen php end card_material --- */
            /* --- gen php begin cardland_material --- */
// # Row 1-3: City (1-18)
    "card_land_1" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 1,
        "r" => "infYellow",
        "d" => "camel",
        "dr" => "upgYellow/2infYellow",
        "tags" => "City",
],
    "card_land_2" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 2,
        "r" => "infYellow",
        "d" => "camel",
        "dr" => "upgYellow/2infYellow",
        "tags" => "City",
],
    "card_land_3" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 3,
        "r" => "upgGrreen(free)",
        "d" => "camel",
        "dr" => "upgGreen,food",
        "tags" => "City",
],
    "card_land_4" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 4,
        "r" => "infAny",
        "d" => "camel",
        "dr" => "upgGreen,infAny",
        "tags" => "City",
],
    "card_land_5" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 5,
        "r" => "pickWorker",
        "d" => "camel",
        "dr" => "2food:cardLand,pickWorker",
        "tags" => "City",
],
    "card_land_6" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 6,
        "r" => "infYellow",
        "d" => "camel",
        "dr" => "2food:cardLand,infYellow",
        "tags" => "City",
],
    "card_land_7" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 7,
        "r" => "infBlue",
        "d" => "camel",
        "dr" => "cardFolk,infBlue",
        "tags" => "City",
],
    "card_land_8" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 8,
        "r" => "infCard",
        "d" => "camel",
        "dr" => "cardFolk,infCard",
        "tags" => "City",
],
    "card_land_9" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 9,
        "d" => "telescope,camel",
        "dr" => "cardSpace,infBlue",
        "tags" => "City Observatory",
],
    "card_land_10" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 10,
        "d" => "telescope,camel",
        "dr" => "cardSpace,infYellow",
        "tags" => "City Observatory",
],
    "card_land_11" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 11,
        "d" => "telescope,camel",
        "dr" => "upgBlack/2infBlack",
        "tags" => "City Observatory",
],
    "card_land_12" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 12,
        "d" => "telescope,camel",
        "dr" => "upgBlack/2infBlack",
        "tags" => "City Observatory",
],
    "card_land_13" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 13,
        "d" => "telescope,camel",
        "dr" => "cardSpace,infBlack",
        "tags" => "City Observatory",
],
    "card_land_14" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 14,
        "d" => "telescope,camel",
        "dr" => "cardSpace(dis)",
        "tags" => "City Observatory",
],
    "card_land_15" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 15,
        "r" => "infYellow",
        "d" => "camel",
        "dr" => "cardFolk,journal",
        "tags" => "City Book",
],
    "card_land_16" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 16,
        "d" => "bird",
        "dr" => "infYellow,journal",
        "tags" => "City Book",
],
    "card_land_17" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 17,
        "d" => "bird",
        "dr" => "infBlue,journal",
        "tags" => "City Book",
],
    "card_land_18" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 18,
        "d" => "telescope,bird",
        "dr" => "infBlack,journal",
        "tags" => "City Book Observatory",
],
// # Row 4-6: Vista (19-37)
    "card_land_19" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 19,
        "r" => "2infCard",
        "dr" => "infCard",
        "tags" => "Vista",
        "trig" => "Stars",
],
    "card_land_20" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 20,
        "r" => "coin",
        "dr" => "food",
        "tags" => "Vista",
        "trig" => "Stars",
],
    "card_land_21" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 21,
        "r" => "coin",
        "dr" => "coin",
        "tags" => "Vista",
        "trig" => "Sea",
],
    "card_land_22" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 22,
        "r" => "infBlue",
        "dr" => "infBlue/infMove",
        "tags" => "Vista",
        "trig" => "Sea",
],
    "card_land_23" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 23,
        "r" => "upgGreen(free)",
        "dr" => "coin/diceMod",
        "tags" => "Vista Observatory",
        "trig" => "Comet",
],
    "card_land_24" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 24,
        "r" => "upgGreen(free)",
        "dr" => "food/infMove",
        "tags" => "Vista Observatory",
        "trig" => "Comet",
],
    "card_land_25" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 25,
        "r" => "reroll",
        "dr" => "coin",
        "tags" => "Vista",
        "trig" => "Vista",
],
    "card_land_26" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 26,
        "r" => "reroll",
        "dr" => "infBlue/infMove",
        "tags" => "Vista",
        "trig" => "Vista",
],
    "card_land_27" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 27,
        "r" => "2coin",
        "dr" => "food",
        "tags" => "Vista",
        "trig" => "Planet/Sun/Moon",
],
    "card_land_28" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 28,
        "r" => "2coin",
        "dr" => "pickWorker",
        "tags" => "Vista",
        "trig" => "Planet/Sun/Moon",
],
    "card_land_29" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 29,
        "r" => "reroll",
        "dr" => "coin",
        "tags" => "Vista",
        "trig" => "City",
],
    "card_land_30" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 30,
        "r" => "reroll",
        "dr" => "infYellow/infMove",
        "tags" => "Vista",
        "trig" => "City",
],
    "card_land_31" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 31,
        "r" => "2coin",
        "dr" => "diceMod,infMove",
        "tags" => "Vista",
        "trig" => "cardFolk",
],
    "card_land_32" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 32,
        "r" => "infCard",
        "dr" => "infCard",
        "tags" => "Vista",
        "trig" => "cardFolk",
],
    "card_land_33" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 33,
        "r" => "coin",
        "dr" => "coin",
        "tags" => "Vista",
        "trig" => "Harbour",
],
    "card_land_34" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 34,
        "r" => "infYellow",
        "dr" => "infYellow/infMove",
        "tags" => "Vista",
        "trig" => "Harbour",
],
    "card_land_35" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 35,
        "r" => "reroll",
        "dr" => "journal",
        "tags" => "Vista",
        "trig" => "Observatory/Book",
],
    "card_land_36" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 36,
        "r" => "reroll",
        "dr" => "food/coin",
        "tags" => "Vista",
        "trig" => "Observatory/Book",
],
// # Row 7: City (38)
    "card_land_37" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 37,
        "r" => "coin",
        "dr" => "food",
        "tags" => "Vista",
        "trig" => "upgAny",
],
    "card_land_38" => [ 
        "create" => 1,
        "location" => "deck_land",
        "type" => "card card_land land",
        "t" => "land",
        "num" => 38,
        "d" => "camel,bird",
        "dr" => "2food:cardLand,journal",
        "tags" => "City Book",
],
            /* --- gen php end cardland_material --- */
            /* --- gen php begin upg_material --- */
    "upg_yellow_1" => [ 
        "type" => "upg upg_yellow",
        "w" => 2,
        "h" => 1,
        "num" => 1,
        "t" => "yellow",
        "r" => "dicePlus",
        "r2" => "camel",
        "vp" => "|1",
],
    "upg_yellow_2" => [ 
        "type" => "upg upg_yellow",
        "w" => 2,
        "h" => 1,
        "num" => 2,
        "t" => "yellow",
        "r" => "camel",
        "r2" => "diceMinus",
        "vp" => "|1",
],
    "upg_yellow_3" => [ 
        "type" => "upg upg_yellow",
        "w" => 2,
        "h" => 1,
        "num" => 3,
        "t" => "yellow",
        "r" => "bird",
        "r2" => "dicePlus",
        "vp" => "|1",
],
    "upg_yellow_4" => [ 
        "type" => "upg upg_yellow",
        "w" => 2,
        "h" => 1,
        "num" => 4,
        "t" => "yellow",
        "r" => "diceMinus",
        "r2" => "bird",
        "vp" => "|1",
],
    "upg_yellow_5" => [ 
        "type" => "upg upg_yellow",
        "w" => 2,
        "h" => 1,
        "num" => 5,
        "t" => "yellow",
        "r2" => "coinDis",
        "vp" => "|1",
],
    "upg_yellow_6" => [ 
        "type" => "upg upg_yellow",
        "w" => 2,
        "h" => 1,
        "num" => 6,
        "t" => "yellow",
        "r" => "coinDis",
        "vp" => "|1",
],
    "upg_blue_7" => [ 
        "type" => "upg upg_blue",
        "w" => 2,
        "h" => 1,
        "num" => 7,
        "t" => "blue",
        "r" => "dicePlus",
        "r2" => "ship",
        "vp" => "|1",
],
    "upg_blue_8" => [ 
        "type" => "upg upg_blue",
        "w" => 2,
        "h" => 1,
        "num" => 8,
        "t" => "blue",
        "r" => "ship",
        "r2" => "diceMinus",
        "vp" => "|1",
],
    "upg_blue_9" => [ 
        "type" => "upg upg_blue",
        "w" => 2,
        "h" => 1,
        "num" => 9,
        "t" => "blue",
        "r" => "ship",
        "r2" => "bird",
        "vp" => "|1",
],
    "upg_blue_10" => [ 
        "type" => "upg upg_blue",
        "w" => 2,
        "h" => 1,
        "num" => 10,
        "t" => "blue",
        "r" => "bird",
        "r2" => "ship",
        "vp" => "|1",
],
    "upg_blue_11" => [ 
        "type" => "upg upg_blue",
        "w" => 2,
        "h" => 1,
        "num" => 11,
        "t" => "blue",
        "r" => "coinDis",
        "r2" => "dicePlus",
        "vp" => "|1",
],
    "upg_blue_12" => [ 
        "type" => "upg upg_blue",
        "w" => 2,
        "h" => 1,
        "num" => 12,
        "t" => "blue",
        "r" => "diceMinus",
        "r2" => "coinDis",
        "vp" => "|1",
],
    "upg_black_20" => [ 
        "type" => "upg upg_black",
        "w" => 1,
        "h" => 2,
        "num" => 20,
        "t" => "black",
        "r" => "ship,bird,camel",
        "vp" => "|2",
],
    "upg_black_21" => [ 
        "type" => "upg upg_black",
        "w" => 1,
        "h" => 2,
        "num" => 21,
        "t" => "black",
        "r" => "diceMod",
        "vp" => "|3",
],
    "upg_black_22" => [ 
        "type" => "upg upg_black",
        "w" => 1,
        "h" => 2,
        "num" => 22,
        "t" => "black",
        "r" => "telescope,foodDis",
        "vp" => "|2",
],
    "upg_green_31" => [ 
        "type" => "upg upg_green",
        "w" => 1,
        "h" => 1,
        "num" => 31,
        "t" => "green",
        "r" => "camel",
        "vp" => 1,
],
    "upg_green_32" => [ 
        "type" => "upg upg_green",
        "w" => 1,
        "h" => 1,
        "num" => 32,
        "t" => "green",
        "r" => "ship",
        "vp" => 1,
],
    "upg_green_33" => [ 
        "type" => "upg upg_green",
        "w" => 1,
        "h" => 1,
        "num" => 33,
        "t" => "green",
        "r" => "telescope",
        "vp" => 1,
],
    "upg_green_34" => [ 
        "type" => "upg upg_green",
        "w" => 1,
        "h" => 1,
        "num" => 34,
        "t" => "green",
        "r" => "bird",
        "vp" => 1,
],
    "upg_pink_40" => [ 
        "type" => "upg upg_pink",
        "w" => 1,
        "h" => 1,
        "num" => 40,
        "t" => "pink",
        "tags" => "Vista",
        "vp" => 1,
],
    "upg_pink_41" => [ 
        "type" => "upg upg_pink",
        "w" => 1,
        "h" => 1,
        "num" => 41,
        "t" => "pink",
        "tags" => "City",
        "vp" => 1,
],
    "upg_pink_42" => [ 
        "type" => "upg upg_pink",
        "w" => 1,
        "h" => 1,
        "num" => 42,
        "t" => "pink",
        "tags" => "Sea",
        "vp" => 1,
],
    "upg_pink_43" => [ 
        "type" => "upg upg_pink",
        "w" => 1,
        "h" => 1,
        "num" => 43,
        "t" => "pink",
        "tags" => "Harbour",
        "vp" => 1,
],
    "upg_pink_44" => [ 
        "type" => "upg upg_pink",
        "w" => 1,
        "h" => 1,
        "num" => 44,
        "t" => "pink",
        "tags" => "Observatory",
        "vp" => 5,
],
    "upg_pink_45" => [ 
        "type" => "upg upg_pink",
        "w" => 1,
        "h" => 1,
        "num" => 45,
        "t" => "pink",
        "tags" => "Book",
        "vp" => 5,
],
    "upg_pink_46" => [ 
        "type" => "upg upg_pink",
        "w" => 1,
        "h" => 1,
        "num" => 46,
        "t" => "pink",
        "tags" => "Planet",
        "vp" => 3,
],
    "upg_pink_47" => [ 
        "type" => "upg upg_pink",
        "w" => 1,
        "h" => 1,
        "num" => 47,
        "t" => "pink",
        "tags" => "Stars",
        "vp" => 5,
],
    "upg_pink_48" => [ 
        "type" => "upg upg_pink",
        "w" => 1,
        "h" => 1,
        "num" => 48,
        "t" => "pink",
        "tags" => "Comet Comet",
        "vp" => 4,
],
    "upg_pink_49" => [ 
        "type" => "upg upg_pink",
        "w" => 1,
        "h" => 1,
        "num" => 49,
        "t" => "pink",
        "tags" => "Comet",
        "vp" => 5,
],
            /* --- gen php end upg_material --- */
        ];
    }

    public function get(): array {
        return $this->token_types;
    }

    /**
     * This has to be called from "initTable" method of game which is when db is conected but action is not started yet
     */
    public function adjustMaterial(Game $game) {
        if ($this->adjusted) {
            return $this->token_types;
        }
        $this->adjusted = true;
        // ... do something reading number or palyer of game options with material

        return $this->token_types;
    }

    function getRulesFor($token_id, $field = "r", $default = "") {
        $tt = $this->token_types;
        $key = $token_id;
        while ($key) {
            $data = $tt[$key] ?? null;
            if ($data) {
                if ($field === "*") {
                    $data["_key"] = $key;
                    return $data;
                }
                return $data[$field] ?? $default;
            }
            $new_key = $this->getPartsPrefix($key, -1);
            if ($new_key == $key) {
                break;
            }
            $key = $new_key;
        }
        //$this->systemAssertTrue("bad token $token_id for rule $field", false);
        return $default;
    }

    /** Find stuff in material file */
    function find(string $field, ?string $value, bool $ignorecase = true) {
        foreach ($this->token_types as $key => $rules) {
            $cur = $rules[$field] ?? null;
            if ($cur == $value) {
                return $key;
            }
            if ($ignorecase && is_string($cur) && strcasecmp($cur, $value) == 0) {
                return $key;
            }
        }
        return null;
    }
    function findByName(string $value, bool $ignorecase = true) {
        return $this->find("name", $value, $ignorecase);
    }

    /**
     * Return $i parts of string (part is chunk separated by _
     * I.e.
     * getPartsPrefix("a_b_c",2)=="a_b"
     *
     * If $i is negative - it will means how much remove from tail, i.e
     * getPartsPrefix("a_b_c",-1)=="a_b"
     */
    static function getPartsPrefix($haystack, $i) {
        $parts = explode("_", $haystack);
        $len = count($parts);
        if ($i < 0) {
            $i = $len + $i;
        }
        if ($i <= 0) {
            return "";
        }
        for (; $i < $len; $i++) {
            unset($parts[$i]);
        }
        return implode("_", $parts);
    }

    /**
     * Set rules for a token (used for testing)
     */
    function setRulesFor(string $token_id, array $rules): void {
        if (!isset($this->token_types[$token_id])) {
            $this->token_types[$token_id] = [];
        }
        $this->token_types[$token_id] = array_merge($this->token_types[$token_id], $rules);
    }
}
